### ISSUE TITLE
GetAllGuildMembers error

### ISSUE THREAD

**Issue by sw1ndlegod** [not-ilinked/Anarchy#1]
System.InvalidOperationException: 'The current state of the connection is not Open.'

client.RequestGuildMembers(new GatewayMemberQuery() { GuildId = guildId, Limit = 0 }); this func throwns exception inside 
public static IReadOnlyList<GuildMember> GetAllGuildMembers(this DiscordSocketClient client, ulong guildId)

the way im calling is
 DiscordSocketClient client = new DiscordSocketClient();
client.Login(token)
var members = client.GetAllGuildMembers(guild_id);

what am i doing wrong?

**Comment by not-ilinked** [comment]
client.Login does not wait for the client to connect to the gateway. Add a listener to client.OnLoggedIn, and have whatever you want done after the client has logged in there.
