### ISSUE TITLE
Unhandled Exception: System.ArgumentException: Requested value 'github' was not found.

### ISSUE THREAD

**Issue by CodeDisease** [not-ilinked/Anarchy#13]
I'm trying to make a ~whois command that shows info about the user

but when i try to show the connected accounts it throws this error:
`Unhandled Exception: System.ArgumentException: Requested value 'github' was not found.`

Here is a screenshot of the code im using:
![image](https://user-images.githubusercontent.com/52953518/87734385-d7496000-c815-11ea-8d03-159ca2feca35.png)

**Comment by not-ilinked** [comment]
Because of the way Anarchy handles Connection types, any unknown values will throw that exception. Github connections are new and therefore a new update with it added is not out yet. If you feel like it, you can modify the AccountType enum yourself.
