### ISSUE TITLE
DiscordVoiceSession.OnUserSpeaking only firing once

### ISSUE THREAD

**Issue by swimingduck** [not-ilinked/Anarchy#15]
Pretty much the title. I created a DiscordVoiceSession object using DiscordSocketClient.JoinVoiceChannel() and attached a function to session.OnUserSpeaking. The event only fires once per user when the user first speaks, and never again (e.g. if there are 5 users in a voice, the event will fire a maximum of 5 times).

**Comment by not-ilinked** [comment]
The current version of Anarchy's voice stuff is pretty poorly written. I'm not exactly sure why it happens, but it'll be fixed by the next update.
