### ISSUE TITLE
How do I join a server using this?

### ISSUE THREAD

**Issue by Someonewhoisaperson** [not-ilinked/Anarchy#17]

**Comment by PBTada** [comment]
are you like fucking retarded joining a array has noting todo with splitting a string

**Comment by greek** [comment]
`.join()` does not make you join a server... these kids 😐

**Comment by MRePotatoes** [comment]
hahahaha bully the idiot for not knowing basic C# hahahahahah

**Comment by greek** [comment]
> hahahaha bully the idiot for not knowing basic C# hahahahahah

Nah Fr Dat Way Fr.... :joy: :joy:

**Comment by MRePotatoes** [comment]
> > hahahaha bully the idiot for not knowing basic C# hahahahahah
> 
> Nah Fr Dat Way Fr.... 😂 😂

he really did `"".Join()`.....

**Comment by Someonewhoisaperson** [comment]
wot, i didnt i did DiscordToken aa = "insertinvitehere";
aa.join();

**Comment by greek** [comment]
> > > > hahahaha bully the idiot for not knowing basic C# hahahahahah
> > > 
> > > 
> > > Nah Fr Dat Way Fr.... 😂 😂
> > 
> > 
> > he really did `"".Join()`.....
> 
> wot, i didnt i did DiscordToken aa = "insertinvitehere";
> aa.join();

Oh no no no.... he doesn't know PepeLaugh

**Comment by Someonewhoisaperson** [comment]
> > > > > hahahaha bully the idiot for not knowing basic C# hahahahahah
> > > > 
> > > > 
> > > > Nah Fr Dat Way Fr.... 😂 😂
> > > 
> > > 
> > > he really did `"".Join()`.....
> > 
> > 
> > wot, i didnt i did DiscordToken aa = "insertinvitehere";
> > aa.join();
> 
> Oh no no no.... he doesn't know PepeLaugh

ok

**Comment by joysticks** [comment]
hhhhhhh

**Comment by Someonewhoisaperson** [comment]
> > > > > hahahaha bully the idiot for not knowing basic C# hahahahahah
> > > > 
> > > > 
> > > > Nah Fr Dat Way Fr.... 😂 😂
> > > 
> > > 
> > > he really did `"".Join()`.....
> > 
> > 
> > wot, i didnt i did DiscordToken aa = "insertinvitehere";
> > aa.join();
> 
> Oh no no no.... he doesn't know PepeLaugh

It says in the anarchy docs to do .Join

**Comment by joysticks** [comment]
no it doesn't

**Comment by AXDZ** [comment]
God 🤡

**Comment by greek** [comment]
He Doesn't Know...

**Comment by free1337** [comment]
LOL

**Comment by HideakiAtsuyo** [comment]
Found in 20 seconds lol

```csharp
using System;
using Discord.Gateway;
using Discord;

namespace AnarchyJoin
{
    class Program
    {
        public static void loginwithjoin(string token, string invite)
        {
            DiscordSocketClient client = new DiscordSocketClient();
            client.Login(token);
            client.JoinGuild(invite);
        }

        static void Main(string[] args)
        {
            Console.WriteLine("Token: ");
            var token = Console.ReadLine();
            Console.WriteLine("Invitation code: ");
            var invite = Console.ReadLine();
            loginwithjoin(token, invite);
        }
    }
}
```

**Comment by HideakiAtsuyo** [comment]
Imagine close and re open an issue for nothing

**Comment by TheBackdoor** [comment]
LLLmfao learn C# and dont skid.


And learn how to use github
