### ISSUE TITLE
ID questions

### ISSUE THREAD

**Issue by xvap** [not-ilinked/Anarchy#19]
1. Is there a Leave Guild from ID function?

2. How do i mass-grab ID's? F.e. to send a message to all my friends at once, or if there is a leave Guild fron ID function, to leave all Guilds.

3. Can you mass create (Guild) invites?

**Comment by not-ilinked** [comment]
1. Yes there is. client.LeaveGuild(id);
2. Vague question.
3. Yes. Just call client.CreateGuild(name, icon, region) multiple times.
