### ISSUE TITLE
File not found on login

### ISSUE THREAD

**Issue by mihabozic123** [not-ilinked/Anarchy#2]
Error:
`System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Security.Permissions, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.`
Login code:  
```
DiscordClient client = new DiscordClient();
client.Token = NewTokenList;
```
i tried with DiscordSocketClient too but got the same result

**Comment by not-ilinked** [comment]
This often happens when you use .NET core, which Anarchy doesn't support. Change to .NET framework and you should be good to go.
