### ISSUE TITLE
Regarding my vague question

### ISSUE THREAD

**Issue by xvap** [not-ilinked/Anarchy#20]
I was asking for a way to get every ID of the servers the user is in, and every Chat ID of friends, who the user can send messages to.

**Comment by not-ilinked** [comment]
A client can get all the guilds it's in by using client.GetGuilds(). To get/create a DM channel with a user, call client.CreateDM(userId).

**Comment by xvap** [comment]
Are the ID's stored in a descending order? fe if i tell the client to output them will it give me this?
-XXXXXXXXXX
-XXXXXXXXXX
-XXXXXXXXXX
-XXXXXXXXXX

**Comment by not-ilinked** [comment]
Don't know what you mean by a "descending order". GetGuilds() returns a list of DiscordGuild objects, each of which containing an Id member.
