### ISSUE TITLE
More information on "MemberListQueryOptions" and "GetGuildChannelMembers" needed

### ISSUE THREAD

**Issue by Whanos** [not-ilinked/Anarchy#21]
Hey there,

I'm trying to use GetGuildChannelMembers to iterate through a server and get a list of users.
There's no infomation in the documentation on what "MemberListQueryOptions" does - but from my testing you can use count to set the limit of grabbed users - but how does index work?
When I try to use GetGuildChannelMembers I only get a maximum of around 800 members in a 2100 user server - and my account can see all 2100.

**Comment by not-ilinked** [comment]
GetGuildChannelMembers() basically returns a chunk of what you'd see in a channel's member list. The member list only contains members that can see that specific channel, so maybe you and your bot are pulling from different channels?

I don't think there's need for documentation on "what MemberListQueryOptions does" as it's painfully obvious already.
If you've ever worked with copying arrays/lists the whole index and count thing should make sense to you. If not, read up on it.

**Comment by Whanos** [comment]
Alright Cheers, I'll keep playing around with it.
