### ISSUE TITLE
GetPaymentMethods() returns System.Collections.Generic.List`1[Discord.PaymentMethod] 

### ISSUE THREAD

**Issue by kamikos** [not-ilinked/Anarchy#22]
`DiscordClient client = new DiscordClient(token);
label1.Text += $"PaymentMethods: {client.GetPaymentMethods()} \n";`

returns 

PaymentMethods: Discord.PaymentMethod

**Comment by Rayonex54** [comment]
Hi @kamikos,

GetPaymentMethods() is a IReadOnlyList !
It returns a list of all the payment methods registered in the user account.

You should try something like :  
`
DiscordClient client = new DiscordClient("token");

foreach (var paymentMethod in client.GetPaymentMethods())
{
  Console.WriteLine(paymentMethod);
  //It will write each 
}
`

**Comment by Rayonex54** [comment]
Hi @kamikos,

GetPaymentMethods() returns a IReadOnlyList.
To get each payment method type registered in the account, you should try something like : 
`DiscordClient client = new DiscordClient("token");
foreach(var paymentMethod in client.GetPaymentMethods())
{
  //Write each payment method type in the console :
  Console.WriteLine(paymentMethod.Type);
}
`
You can get many other things from the payment method like billing address etc... (like `paymentMethod.BillingAddress`).

I am French so I hope my English is correct !
