### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by d4rkJordan** [not-ilinked/Anarchy#23]
ShardedClients for bots
Ability to grab current UserClient phone number

**Comment by not-ilinked** [comment]
Getting the client's user's phone number is being added in the next version.

I haven't really decided on whether or not i want to add sharding (i haven't really been asked to look into it lol).
If you could sum it up for me that'd be great.

**Comment by not-ilinked** [comment]
Yeah sharding's coming out in the next version
