### ISSUE TITLE
Doesn't work for Bot Accounts

### ISSUE THREAD

**Issue by ytmcgamer** [not-ilinked/Anarchy#24]
The api doesn't work for bot account can you fix it lol
[screen](https://media.wtf/33074588)

**Comment by MarcoD1337** [comment]
Did you put the word "Bot" in front of the token, if not discord will not register it as a bot.

**Comment by ytmcgamer** [comment]
oh really lemme try

**Comment by ytmcgamer** [comment]
nope still the same 
![image](https://user-images.githubusercontent.com/66328734/93013006-06c1e200-f5a5-11ea-9c73-a32a5c3a358c.png)

**Comment by TheBackdoor** [comment]
Put it like this: "Bot: token" or "Bot: toke"
(i forgot how to do it but its something like this)

**Comment by ytmcgamer** [comment]
oh thanks it worked :)
