### ISSUE TITLE
How do i install this? there's no instructions.. (FIXED..)

### ISSUE THREAD

**Issue by pIOS-the-first** [not-ilinked/Anarchy#26]
How do i install this?

**Comment by minegamer2000** [comment]
lmao

**Comment by Rayonex54** [comment]
Close if fixed

**Comment by pIOS-the-first** [comment]
Ok.

Note: If your seeing this email with no numbers after this message something is wrong client-side. 11111
Joseph Frost email account.

**Comment by pIOS-the-first** [comment]
> Close if fixed

How do i close this??
