### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Synpaste** [not-ilinked/Anarchy#2641]
discord.net does not work. It has a bug where it closes my application and runs a program called KYLGGER.exe. Please fix this issues as I am selling my selfbot!

**Comment by Synpaste** [comment]
se

**Comment by not-ilinked** [comment]
hi

**Comment by Synpaste** [comment]
hello

**Comment by Synpaste** [comment]
want to play minbecraft after school today

**Comment by not-ilinked** [comment]
sure :)

**Comment by faith** [comment]
Troll issue, name doesn't tell anything about it either.

**Comment by Synpaste** [comment]
shut up aldas cringe boy 🤢🤢🤢🤮

**Comment by JustGoodGame** [comment]
h

**Comment by stop-bark** [comment]
idk close it, waste of a issue.

**Comment by owersite** [comment]
close this.
