### ISSUE TITLE
System.PlatformNotSupportedException : 'Operation is not supported on this platform.'

### ISSUE THREAD

**Issue by NaNonnI** [not-ilinked/Anarchy#3119]
When I do "client.Login" it say System.PlatformNotSupportedException : 'Operation is not supported on this platform.'

(I take the exemple of the documentation) then IDK why it's not working because when I write a wrong token It say "InvalidToken Exception"
But when it's a good token it say System.PlatformNotSupportedException

Then my code is right, No?

System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Operation is not supported on this platform.
  Source=System.Private.CoreLib
  Arborescence des appels de procédure :
   at System.Action`1.BeginInvoke(T obj, AsyncCallback callback, Object object)
   at WebSocketSharp.WebSocket.open()
   at WebSocketSharp.WebSocket.Connect()
   at Discord.WebSockets.DiscordWebSocket`1.Connect()
   at Discord.Gateway.DiscordSocketClient.Login(String token)
   at VANITYEXE.Program.Load() in Program.cs:line 96
   at VANITYEXE.Program.Main(String[] args) in Program.cs:line 19

And I use Windows 10.

**Comment by GoByeBye** [comment]
If its saying invalid toke exception you're putting a token that doesn't work

**Comment by NaNonnI** [comment]
No, it's say that because I wrote a bad token (for testing if it's work) but when it's a good token it's say System.PlatformNotSupportedException

**Comment by not-ilinked** [comment]
This often happens when you try to use Anarchy on .NET Core. Anarchy's only targeted at .NET Framework for now, sorry

Tell me if switching helps :)

**Comment by NaNonnI** [comment]
> This often happens when you try to use Anarchy on .NET Core. Anarchy's only targeted at .NET Framework for now, sorry
> 
> Tell me if switching helps :)

Owh.. And how can I switch to to Net Framework ?

**Comment by NaNonnI** [comment]
> > This often happens when you try to use Anarchy on .NET Core. Anarchy's only targeted at .NET Framework for now, sorry
> > Tell me if switching helps :)
> 
> Owh.. And how can I switch to to Net Framework ?

No okey it's good I have installed the lastest Net framerwork at :
https://dotnet.microsoft.com/download/dotnet-framework/net48

And in the .csproj replace the the target framework by 
<TargetFramework>net48</TargetFramework>

I say it because if someone have the same issue.. then.. voila x)

*Awh my english is SO BAD*

Thx all!
