### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by Stanley-GF** [not-ilinked/Anarchy#3120]
bruh its a token grabber u know , i deobfuscated all ur code and i have the ultimate proof ur a token grabberer, u build anarchy grabber and this lib has the same name. and u skidded mscorlib (proof https://cdn.discordapp.com/attachments/767774932494188544/786334368050053120/unknown.png) and its illegal, u promote selfbot, i reported u bye bye, auf wiedorzen , au revoir, 

Regards

-Stan

**Comment by minegamer2000** [comment]
uninstalling now

thank you for warning me i will never trust ilinked again >:(

**Comment by faith** [comment]
Troll issue.

**Comment by Stanley-GF** [comment]
ok boss

**Comment by Stanley-GF** [comment]
1.

**Comment by Stanley-GF** [comment]
sorry i have tried a thing

**Comment by Ri210** [comment]
CHEH
