### ISSUE TITLE
command listener chat

### ISSUE THREAD

**Issue by Skided** [not-ilinked/Anarchy#3181]
ok so basiclly how to do so after user do !start and its starting the command on command listner 
but then its saying "please send file" and the bot will recive the file that the user send/recive the input that the user send

**Comment by Cystemzz** [comment]
What? Can you please rephrase your question so we can understand it.

**Comment by not-ilinked** [comment]
That is one long sentence @Skided 
Anarchy's command handler doesn't support this, so i think the best way to do it would be having a Dictionary with a user ID as the key, and as some info about the chat as the value.
