### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JBellford** [not-ilinked/Anarchy#3184]
Report Function

**Comment by JReverse** [comment]
@JBellford Just automate the webform https://dis.gd/request

Or if you meant Report as a server owner on ban / message delete. Then Possible.

**Comment by JBellford** [comment]
Yep simply talking about the report function for server admins that caches the message being reported on discords side so it being deleted is irrelevant. Ive seen a few things saying early members of discord were given access to this report function allowing in app reporting(yes in dms aswell).

**Comment by not-ilinked** [comment]
I lost the endpoint for that lul

**Comment by stop-bark** [comment]
> I lost the endpoint for that lul

https://discord.com/api/v8/report ig?

method: post
success status code: 201

payload:
  channel_id:"channelidhere"
  guild_id:"guildidhere"
  message_id:"messageidhere"
  reason: [from 0 to 4]
  reason list: 0 = illegal content, 1 = harrasment, 2 = spam or phishing links, 3 = self harm, 4 = nsfw content

**Comment by JBellford** [comment]
I was literally about to post the same thing lol

**Comment by stop-bark** [comment]
lmao

**Comment by JBellford** [comment]
Also another thing to add would be the ability to set the Mobile Indicator

**Comment by stop-bark** [comment]
> Also another thing to add would be the ability to set the Mobile Indicator

not sure how that works lol

**Comment by JBellford** [comment]
https://luna.gitlab.io/discord-unofficial-docs/mobile_indicator.html

**Comment by not-ilinked** [comment]
thanks, i'll be adding the report thing later today.

**Comment by JBellford** [comment]
^ ETA? iirc still isnt in

**Comment by not-ilinked** [comment]
I completely forgot about this issue, sorry. A commit containing it will be commited soon.
