### ISSUE TITLE
Sending Friend Request With Discriminators Starting With Zeros Wont Work

### ISSUE THREAD

**Issue by SmallPP420** [not-ilinked/Anarchy#3187]
I was making a test tool to simply send a friend request before realising quickly that discriminators starting with zeros wont work would there be a way to fix this possibly?

**Comment by not-ilinked** [comment]
If a discriminator is displayed as 0069, the actual numeraical value is 69. Hope that helps :)

**Comment by SmallPP420** [comment]
oh i see now! thanks
