### ISSUE TITLE
Guild member verification

### ISSUE THREAD

**Issue by Zinvoke** [not-ilinked/Anarchy#3193]
Is this already implemented or no? when you join some guilds it seems to be stopping the ability to get the member list

**Comment by not-ilinked** [comment]
Not sure what you mean by "guild member verification", but the client.GetGuildChannelMembers() method does not work very well for huge servers like Fortnite, Minecraft or Among Us.

**Comment by Zinvoke** [comment]
the method to get the guild members isn't returning any users on a larger guild for me

**Comment by JReverse** [comment]
@not-ilinked I think  he may mean member verification screening on community guilds

**Comment by Zinvoke** [comment]
yeah thats what I mean does it prevent grabbing server members?
