### ISSUE TITLE
Get messages through messageID

### ISSUE THREAD

**Issue by Throndax57** [not-ilinked/Anarchy#3195]
I want to know how to get the contents of a messages through its ID.

Because I want my bot to get the contents of a message that recieves a reaction. I'm using client.OnMessageReactionAdded to detect the reactions.

**Comment by not-ilinked** [comment]
This can prove a little difficult with the way Discord works. You're not allowed to GET a single message (afaik), and caching all messages would take up a LOT of memory. If you really want to tho, you could have a Dictionary with the message ID as it's key, and it's contents as the value.

**Comment by Throndax57** [comment]
Thank you
