### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by devnexa** [not-ilinked/Anarchy#3197]
Moving the login code to another thread worked perfectly but now all events are not working. Couldn't find anything in the internet. No matter where i put the events or what i try

**Comment by Zinvoke** [comment]
I had some problems with a couple events aswell

**Comment by devnexa** [comment]
For me every event isn't working. Login works, checking Discords username and stuff works. But the events are simply not getting triggered

**Comment by not-ilinked** [comment]
Make sure you set the API version to 6

**Comment by devnexa** [comment]
> Make sure you set the API version to 6

Are you kidding me ? Version 6 has so much less features that making a selfbot would be a complete waste of time.

**Comment by JReverse** [comment]
@devnexa https://discord.com/developers/docs/reference try v7 then ig may have more.

**Comment by Throndax57** [comment]
I'm having a similar problem of the events not working even if I'm using APIversion = 6

**Comment by stop-bark** [comment]
> So the problem will be fixed in the next anarchy update ?

You can close this issue, and you can also use the dev branch which fixed api ver 8, which you can find [here](https://github.com/not-ilinked/Anarchy/tree/dev)
