### ISSUE TITLE
CreateCommandHandler / CommandBase No Longer working?

### ISSUE THREAD

**Issue by JReverse** [not-ilinked/Anarchy#3198]
CreateCommandHandler / CommandBase No Longer working? It worked yesterday now it's broke.

Commands don't respond at all.

**Comment by not-ilinked** [comment]
Make sure no exceptions are happening and that you are setting the API version to 6. That works for me...

**Comment by JReverse** [comment]
@not-ilinked any plans to fix v8?

**Comment by not-ilinked** [comment]
Pretty sure i have. Just haven't released it yet ;D

**Comment by stop-bark** [comment]
v7 works just fine

**Comment by JReverse** [comment]
@not-ilinked thx <3 will close this
