### ISSUE TITLE
 OnLoggedIn event not working or endless Connecting

### ISSUE THREAD

**Issue by DS1NC-DesConnet** [not-ilinked/Anarchy#3199]
I did as in the documentation I used the Gateway client, created the OnLoggedIn event, started it and ... The bot seemed to start, but it was not displayed in the console that the bot was launched (It was in the OnLoggedIn event) I look at State and it says Connecting

**Comment by VerityProjects** [comment]
This has been an issue for ages, everything else works unless I use the OnLoggedIn event.

**Comment by VerityProjects** [comment]
> I did as in the documentation I used the Gateway client, created the OnLoggedIn event, started it and ... The bot seemed to start, but it was not displayed in the console that the bot was launched (It was in the OnLoggedIn event) I look at State and it says Connecting

Found a fix, something happened in Anachy 0.8.0.1, Downgrade to 0.8.0. Works fine for me.

**Comment by VerityProjects** [comment]
> I did as in the documentation I used the Gateway client, created the OnLoggedIn event, started it and ... The bot seemed to start, but it was not displayed in the console that the bot was launched (It was in the OnLoggedIn event) I look at State and it says Connecting

I lied, it worked for me a couple times, assume it fixed the issue but now its back to a constant connecting.

**Comment by VerityProjects** [comment]
Use ''DiscordSocketClient client = new DiscordSocketClient(new DiscordSocketConfig() { ApiVersion = 7 });''
instead of DiscordSocketClient client = new DiscordSocketClient();
API v8 is broken

**Comment by DS1NC-DesConnet** [comment]
Thx it's work
