### ISSUE TITLE
Error while trying to Edit Messages in DMs

### ISSUE THREAD

**Issue by ytmcgamer** [not-ilinked/Anarchy#3200]
So when I try to do

`client.EditMessage(userid, msgid, "test");`

it gives me an error: Discord.DiscordHttpException: 10003 Unknown Channel

I don't know what I'm doing wrong, any clues?

**Comment by Tescoo** [comment]
PrivateChannel chanol = client.CreateDM(userid).ToDMChannel();
client.EditMessage(userid, msgid, "negro");

**Comment by ytmcgamer** [comment]
doesnt work

**Comment by Tescoo** [comment]
cap
