### ISSUE TITLE
I don't even know how to use Anarchy! XD 

### ISSUE THREAD

**Issue by RandomUserz** [not-ilinked/Anarchy#3203]
Can someone tell me how to set it up? I just downloaded it now I don't know what to do with it. I can't figure it out. I never did one of these things before. Like does it switch out your normal discord or what? I don't even know how to switch the files for discord to other things. God I'm a fucking Idiot... Will anyone help me? or does Anarchy not work anymore?

**Comment by doffo** [comment]
You could check out some examples in the example folder. If you need help for how to set it up lmk.

**Comment by doffo** [comment]
(It ofcourse still works.)
