### ISSUE TITLE
Having problems on some accounts

### ISSUE THREAD

**Issue by Throndax57** [not-ilinked/Anarchy#3204]
The events sometimes doesn't or stops working for some discord accounts. I'm using Api Version 6

**Comment by not-ilinked** [comment]
Make sure you're using the updated version on the dev branch. I fixed a few things there.

**Comment by Throndax57** [comment]
Where can I get the dev branch version?

**Comment by stop-bark** [comment]
> Where can I get the dev branch version?

https://github.com/not-ilinked/Anarchy/tree/dev
