### ISSUE TITLE
Gateway did not respond with a server

### ISSUE THREAD

**Issue by REVENGE977** [not-ilinked/Anarchy#3205]
i get `System.TimeoutException: 'Gateway did not respond with a server'`

when i try to connect to a voice channel
```cs
DiscordVoiceSession session = client.JoinVoiceChannel(new VoiceStateProperties { ChannelId = channelId, GuildId = guildId });
```

**Comment by REVENGE977** [comment]
btw i have the voice binaries,
the bot joins the voice channel and everything but, i `OnConnected` event doesn't work.

**Comment by REVENGE977** [comment]
probably all the voice events don't work either .

**Comment by stop-bark** [comment]
did you set ur api ver to 7, or u can also use the dev branch which fixed ver 8

**Comment by not-ilinked** [comment]
This can happen if you don't have opus.dll, ffmpeg.exe and libsodium.dll in the same directory as ur executable.
