### ISSUE TITLE
Offtopic issue

### ISSUE THREAD

**Issue by MapleHackersoff** [not-ilinked/Anarchy#3206]
can u create Guilded Wrapper?
https://www.guilded.gg/

**Comment by stop-bark** [comment]
more of a question not a issue

**Comment by iphqne** [comment]
i doubt iLinked will wanna do this, maybe have a go yourself?

**Comment by not-ilinked** [comment]
making a wrapper for guilded would just be punching down. their backend is literally written in PHP lmfao
