### ISSUE TITLE
Anarchy not working

### ISSUE THREAD

**Issue by kamikos** [not-ilinked/Anarchy#3209]
Problem is with clients
401: Unauthorized
Tested on api version: 6, 8
master and dev branch 
this happens since 1 April
programs that used to work before dont work now

**Comment by stop-bark** [comment]
did u use the correct token?

**Comment by kamikos** [comment]
Yes

**Comment by kamikos** [comment]
I can force some actions like sendig message with DiscordClient but DiscordSocketClient On LoggedIn wont fire

**Comment by kamikos** [comment]
`using System;
using System.Threading;
using Discord.Gateway;

namespace ConsoleApp1
{
    class Program
    {
      
        static void Main(string[] args)
        {
            DiscordSocketClient client = new DiscordSocketClient(new DiscordSocketConfig()
            {
                ApiVersion = 7
            });
            client.OnLoggedIn += Client_OnLoggedIn;
            Console.Write("Token: ");
            client.Login(Console.ReadLine());

            Thread.Sleep(-1);
        }

        private static void Client_OnLoggedIn(DiscordSocketClient client, LoginEventArgs args)
        {
            Console.WriteLine("Logged in as " + args.User.Username);
        }
    }
}
`
quick example that does not work for me (using dev branch)

**Comment by kamikos** [comment]
Uh so tested it with more accs and it seems to only work for non nitro accounts

**Comment by stop-bark** [comment]
huh let me try with a nitro acc

**Comment by stop-bark** [comment]
![image](https://user-images.githubusercontent.com/60797172/113735370-dc806f00-9704-11eb-9a7f-f428db30df64.png)
seems to still work for me

**Comment by kamikos** [comment]
not nitro
![image](https://user-images.githubusercontent.com/36669411/113752646-7ba96480-970d-11eb-99b8-7872a389b3ee.png)
nitro
![image](https://user-images.githubusercontent.com/36669411/113752736-98459c80-970d-11eb-850b-291c6c3523f4.png)
idk its kinda random then

**Comment by kamikos** [comment]
made new acc and it works
![image](https://user-images.githubusercontent.com/36669411/113754988-16a33e00-9710-11eb-8949-4442b3dc4343.png)

**Comment by iphqne** [comment]
are you using this dev build? a new channel type called the "Stage" channel came out and iLinked has only fixed it in the dev build so far

**Comment by kamikos** [comment]
yes

**Comment by iphqne** [comment]
you'll need to actually debug anarchy then and see why you're not being properly logged in

**Comment by not-ilinked** [comment]
any updates on this issue?

**Comment by kamikos** [comment]
im just using diffrent account and it works

**Comment by epic6969** [comment]
same issue for me
![Untitled](https://user-images.githubusercontent.com/60292167/115932354-11265180-a48d-11eb-97d6-447b647b759f.png)

**Comment by iphqne** [comment]
> are you using the dev build? a new channel type called the "Stage" channel came out and iLinked has only fixed it in the dev build so far, your Anarchy.dll should be 603kb

@epic6969

**Comment by epic6969** [comment]
> 
> 
> > are you using the dev build? a new channel type called the "Stage" channel came out and iLinked has only fixed it in the dev build so far, your Anarchy.dll should be 603kb
> 
> @epic6969

where can i get that?

**Comment by iphqne** [comment]
> > 
> 
> > 
> 
> > > are you using the dev build? a new channel type called the "Stage" channel came out and iLinked has only fixed it in the dev build so far, your Anarchy.dll should be 603kb
> 
> > 
> 
> > @epic6969
> 
> 
> 
> where can i get that?


https://github.com/not-ilinked/Anarchy/tree/dev, make sure you download the source and build it yourself as the "release" dll is old

**Comment by epic6969** [comment]
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > > are you using the dev build? a new channel type called the "Stage" channel came out and iLinked has only fixed it in the dev build so far, your Anarchy.dll should be 603kb
> > 
> > 
> > > 
> > 
> > 
> > > @epic6969
> > 
> > 
> > where can i get that?
> 
> https://github.com/not-ilinked/Anarchy/tree/dev, make sure you download the source and build it yourself as the "release" dll is old

thanks worked 
![bilde](https://user-images.githubusercontent.com/60292167/115935863-6580ff80-a494-11eb-89fd-a9901fcacd12.png)

**Comment by iphqne** [comment]
np, @not-ilinked this topic was inactive until this guy had the same issue and now his is resolved, lock maybe?

**Comment by iphqne** [comment]
> > 
> 
> > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > > are you using the dev build? a new channel type called the "Stage" channel came out and iLinked has only fixed it in the dev build so far, your Anarchy.dll should be 603kb
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > @epic6969
> 
> > > 
> 
> > > 
> 
> > > where can i get that?
> 
> > 
> 
> > https://github.com/not-ilinked/Anarchy/tree/dev, make sure you download the source and build it yourself as the "release" dll is old
> 
> 
> 
> thanks worked 
> 
> ![bilde](https://user-images.githubusercontent.com/60292167/115935863-6580ff80-a494-11eb-89fd-a9901fcacd12.png)
> 
> 

np

**Comment by iphqne** [comment]
> im just using diffrent account and it works

i guarantee you're not using the dev build, make sure you're downloading the source and compiling it yourself

**Comment by stop-bark** [comment]
> 
> 
> > im just using diffrent account and it works
> 
> i guarantee you're not using the dev build, make sure you're downloading the source and compiling it yourself

he literally did, he mentioned he tried api 6 and 8, and master and dev branch

**Comment by iphqne** [comment]
> > > im just using diffrent account and it works
> > 
> > 
> > i guarantee you're not using the dev build, make sure you're downloading the source and compiling it yourself
> 
> he literally did, he mentioned he tried api 6 and 8, and master and dev branch

i guarantee he used the release from the dev build (old dll) instead of building it and compiling it himself

**Comment by kamikos** [comment]
i guarantee i used the dev branch and compiled myself ¯\_(ツ)_/¯

**Comment by not-ilinked** [comment]
Can anyone sum up what the current state of this issue is? I'm working on an update so now is the time.

**Comment by kamikos** [comment]
```

        public static DiscordSocketClient client = new DiscordSocketClient(new DiscordSocketConfig()
        {
            Cache = false
        });

```
this was fixing it for me
