### ISSUE TITLE
Embeds array always empty

### ISSUE THREAD

**Issue by AsianPotato** [not-ilinked/Anarchy#3212]
If I send a webhook with an embed in it and receive it with OnMessageReceived the embeds array should have the embed inside it but its empty. This also started happening today with a nodejs library I've been using (discord-user-bots). This happened both on the dev branch and normal branch. It was working fine yesterday, has discord changed something? It seems that the content is also empty

This is the webhook I sent: https://i.imgur.com/wfOJnqM.png
This is what discord receives: https://i.imgur.com/BoPLthF.png
This is what the user bot socket sees:
```
{
  "author": {
    "avatar": null,
    "public_flags": 0,
    "flags": 0,
    "bot": true,
    "id": OMITTED,
    "username": "Captain Hook",
    "discriminator": 0,
    "Avatar": null,
    "Badges": 0,
    "Type": 2,
    "Hypesquad": 0,
    "CreatedAt": "2020-12-01T05:26:18.807+00:00"
  },
  "member": null,
  "attachments": [
    
  ],
  "embeds": [
    
  ],
  "channel_id": OMITTED,
  "id": OMITTED,
  "content": "",
  "tts": false,
  "Author": {
    "User": {
      "avatar": null,
      "public_flags": 0,
      "flags": 0,
      "bot": true,
      "id": OMITTED,
      "username": "Captain Hook",
      "discriminator": 0,
      "Avatar": null,
      "Badges": 0,
      "Type": 2,
      "Hypesquad": 0,
      "CreatedAt": "2020-12-01T05:26:18.807+00:00"
    },
    "Member": null
  },
  "Attachment": null,
  "Embed": null,
  "reactions": [
    
  ],
  "mentions": [
    
  ],
  "mention_roles": [
    
  ],
  "mention_everyone": false,
  "timestamp": "2021-04-30T17:55:28.454+01:00",
  "edited_timestamp": null,
  "pinned": false,
  "Channel": {
    "id": OMITTED
  },
  "guild_id": OMMITTED,
  "Guild": {
    "id": OMMITTED
  },
  "type": 0,
  "flags": 0
}
```

**Comment by not-ilinked** [comment]
I'm having a hard time reproducing this. This is my code, please correct me if i'm doing something wrong:

`cs
static void Main()
        {
            DiscordSocketClient client = new DiscordSocketClient();
            client.OnMessageReceived += Client_OnMessageReceived;
            client.Login("token");

            Thread.Sleep(-1);
        }

        private static void Client_OnMessageReceived(DiscordSocketClient client, Discord.Gateway.MessageEventArgs args)
        {
            if (args.Message.Author.User.Type == DiscordUserType.Webhook)
            {
                // breakpoint (here args.Embed is not null)
            }
        }`

**Comment by not-ilinked** [comment]
The github comment is kinda broken but idk how to fix, lol

**Comment by not-ilinked** [comment]
Closed due to inactivity.
