### ISSUE TITLE
Feature Request: Play videos on Screenshare

### ISSUE THREAD

**Issue by xenos1337** [not-ilinked/Anarchy#3213]
I'm not sure if that is already a feature but I don't think it is so you can choose a file like .mp4, webm, etc and then play it when starting a screenshare

**Comment by not-ilinked** [comment]
I did plan to add this, but because of a lack of documentation it's hard to figure out how to.

**Comment by xenos1337** [comment]
I think you have to make a websocket to ://server-location.discord.media/?v=5 not sure tho

**Comment by not-ilinked** [comment]
Yes. Much of the connection and authentication process is identical to that of voice servers, it's more just an issue of not knowing what data to send. Anarchy already has support for starting and watching streams, getting previews, and more.

**Comment by not-ilinked** [comment]
Closed due to inactivity.
