### ISSUE TITLE
[enhancement] Get the reply text someone is replying to

### ISSUE THREAD

**Issue by sezonis** [not-ilinked/Anarchy#3219]
You know that new "reply" feature? I don't think there is a way of getting the text someone is replying to at this moment. 

Wondering if it could be added in?

**Comment by not-ilinked** [comment]
This is in the new update.
![billede](https://user-images.githubusercontent.com/66884346/120822396-a91c5e00-c556-11eb-85bf-d538bc2d1c2a.png)

The changes have been pushed to the dev branch, so if this is something you want to try out right now, go build it from there :)

**Comment by sezonis** [comment]
> This is in the new update.
> ![billede](https://user-images.githubusercontent.com/66884346/120822396-a91c5e00-c556-11eb-85bf-d538bc2d1c2a.png)
> 
> The changes have been pushed to the dev branch, so if this is something you want to try out right now, go build it from there :)

Thank you very much! I just have a question, content for whatever reason in DM's is showing as an empty string through OnMessageRecieved, even though I have DiscordGatewayIntent.DirectMessages enabled. Am I doing something wrong? 

The reply reference works like a charm. It's just private messages that don't seem to anymore. Text channel messages return the content just fine, private messages is always an empty string (even if you do/don't use the reply feature) not matter what you do.
