### ISSUE TITLE
Buying nitro doesnt work?

### ISSUE THREAD

**Issue by m1lxs** [not-ilinked/Anarchy#3220]
I've been experimenting with your Library a little bit and found the buy nitro method, tried it, and found out it does not work.
Will there be a fix to this? 
I've put it in a try catch and got the message "Authenticating", idk if its just me having this problem.

**Comment by not-ilinked** [comment]
That's not an issue with Anarchy but with your payment method. It may partially be because Anarchy's requests don't look 100% legit to Discord, but the right data IS being sent.
