### ISSUE TITLE
Anarchy destroys tokens

### ISSUE THREAD

**Issue by Terribilis1337** [not-ilinked/Anarchy#3221]
Anarchy somehow destroys the tokens (need to get verified)

**Comment by not-ilinked** [comment]
What method(s) do you call for this to happen?

**Comment by Terribilis1337** [comment]
I'll make some tests, but I know, that it happend when I let the tokens join a server

**Comment by Terribilis1337** [comment]
Okay, I tested some modules, only the Join-method seems to destroy them. And I think there is a connection problem with the DiscordSocketClients

**Comment by not-ilinked** [comment]
Accounts getting terminated when joining guilds is an issue many have had, and it's not just with Anarchy. I'll try to fix it.

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/119569414-ff4b0d80-bdae-11eb-979f-2ae57fb7ad60.png)
I think this can help

**Comment by sw1ndle666** [comment]
dm channel methods related also terminates ur account very quick, message doesn't matter.

**Comment by Terribilis1337** [comment]
> dm channel methods related also terminates ur account very quick, message doesn't matter.
Couldn't it be cuz of the action itself? I heard Discord is really strict, when you DM-advertise. Did you use Full-Verified tokens?

**Comment by sw1ndle666** [comment]
> > dm channel methods related also terminates ur account very quick, message doesn't matter.
> > Couldn't it be cuz of the action itself? I heard Discord is really strict, when you DM-advertise. Did you use Full-Verified tokens?

they do ban and are very strict, but until recently bans were given after couple of days. now they are instant after first 1-2 messages no matter what message i sent through anarchy api either its random or specific. and i did tested in fact all posibilities with full verified tokens by phone+email. they do get banned after first or second message sent in dm. and also tried to send manually same type of messages manually from browser, accounts wouldnt get banned if i would send them myself so it wasn't my algorithms or messages.

**Comment by not-ilinked** [comment]
Hi. I can confirm that i have figured out a "bypass" for the issue with joining guilds, which might also help with things like mass-DM'ing, although i'm not 100% sure.
