### ISSUE TITLE
ammm i think i found a bug or i dont now whats happening 

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3222]
when i put the code in the start cs works correcly but when the code is in a class not :( help

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/119570782-d4fa4f80-bdb0-11eb-878f-fc203e588c4c.png)
this is the code

**Comment by Mrgaton** [comment]
The program gets stuk in 
DiscordClient dclient = new DiscordClient(txtToken.Text.Replace("\n", ""));

**Comment by Mrgaton** [comment]
And this 
![image](https://user-images.githubusercontent.com/68958481/119638776-453bbc00-be17-11eb-8cc9-cc940aaa567a.png)

**Comment by Mrgaton** [comment]
here is my proyect souscre code 
[RaidTestUsingAnarchy.zip](https://github.com/not-ilinked/Anarchy/files/6546181/RaidTestUsingAnarchy.zip)

**Comment by kovakovi2000** [comment]
![image](https://user-images.githubusercontent.com/29395270/119763656-381edb80-beb0-11eb-8e43-6b62db6fe5eb.png)
Simular problem here when `client.GetGuilds()`
(tried with & without this:
`Intents = DiscordGatewayIntent.Guilds | DiscordGatewayIntent.GuildMessages`)
Also OnLoggedIn and OnMessageReceived did get called many times when the user already have information about itself like nickname, but if I use the 0.7 it get called ever time just other functions won't work

_(This API is amazing thanks for your hard work)_

**Comment by not-ilinked** [comment]
This issue with permissions has been noted and will be fixed in the next update.
