### ISSUE TITLE
Anarchy not start in a function

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3223]
I have the code for login whith anarchy presing a button but the program frece and dont do anithing
Help

**Comment by xenos1337** [comment]
in a winform?

**Comment by Mrgaton** [comment]
yes in a windows.form

**Comment by kamikos** [comment]
use multiple threads

**Comment by xenos1337** [comment]
make a new background worker and put the bot code in there and then start the background worker
