### ISSUE TITLE
Not all servers triggering OnMessageReceived using DiscordSocketClient

### ISSUE THREAD

**Issue by zengavoid** [not-ilinked/Anarchy#3225]
When I create a private server everything comes across fine, but when I join r/wallstreetbets the messages do not trigger the OnMessageReceived.  I wonder if it has somthing to do with the channel features that are on this channel..

the private server I have does not have any features but the wallstreetbets server has the following features:  I get these values by enumerating client.GetGuilds

&nbsp; | Name | Value | Type
-- | -- | -- | --
&nbsp; | [0] | "WELCOME_SCREEN_ENABLED" | string
&nbsp; | [1] | "ANIMATED_ICON" | string
&nbsp; | [2] | "COMMUNITY" | string
&nbsp; | [3] | "BANNER" | string
&nbsp; | [4] | "NEWS" | string
&nbsp; | [5] | "VANITY_URL" | string
&nbsp; | [6] | "RELAY_ENABLED" | string
&nbsp; | [7] | "ENABLED_DISCOVERABLE_BEFORE" | string
&nbsp; | [8] | "PREVIEW_ENABLED" | string
&nbsp; | [9] | "INVITE_SPLASH" | string
&nbsp; | [10] | "DISCOVERABLE" | string
&nbsp; | [11] | "MEMBER_VERIFICATION_GATE_ENABLED" | string

**Comment by zengavoid** [comment]
Did a bit more poking around and it appears to be an issue with any server that is listed in the *public discord servers

**Comment by Laar-u** [comment]
> 
> 
> Did a bit more poking around and it appears to be an issue with any server that is listed in the *public discord servers

Any Official servers won't work with this, and I also think if it's above a specific amount of people, but over 3k works 100%, idk the actual amount

**Comment by zengavoid** [comment]
is there any work around to log activity on official servers?

**Comment by not-ilinked** [comment]
I'm aware of this issue, but i'm not sure how to fix it. It's very difficult to log what discord's own client sends and receives from the gateway bcuz of zlib compression and such. If anyone knows how to log these things in plain text please post it here...

**Comment by zengavoid** [comment]
where in the code can I set a break point to see the ignored  payload?  I can take a crack at the zlib compression but Im having a hard time finding where to get ahold of it.

**Comment by not-ilinked** [comment]
There are no "ignored" payloads. I have just used Developer Tools to get the messages, but again the zlib compression makes it impossible to understand what's being received from the server (unless you could decompress it, of course).

**Comment by not-ilinked** [comment]
This issue is solved in the new commit. You can now use the 'SubscribeToGuildEvents()' method to begin listening.
