### ISSUE TITLE
What is the possibility of being banned using this API?

### ISSUE THREAD

**Issue by TH3AL3X** [not-ilinked/Anarchy#3226]

**Comment by Laar-u** [comment]
Well joining servers currently will instantly ban you, I suggest you to test everything on alts

**Comment by TH3AL3X** [comment]
Ya and if i didn't used the "join" feature? only the other stuff, just SendMessages etc...?

**Comment by Enum0x539** [comment]
You can use almost everything without getting banned.

**Comment by xenos1337** [comment]
used this on my main since ages never got banned ¯\_(ツ)_/¯

**Comment by not-ilinked** [comment]
Discord has added TLS fingerprinting to some of their endpoints (joining guilds for an example). I'll release a fix for this issue soon, but in the mean time feel free to add other endpoints this happens on to the issue.

**Comment by not-ilinked** [comment]
Closed due to inactivity.
