### ISSUE TITLE
Anarchy freeze on a windows form function

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3230]
Pleas Ilinked create an windows work and put a textbox and a button for login whith anarchy in the form please there is an bug thath freze alll

**Comment by Laar-u** [comment]
stop being a dumbass and run the bot in a different thread than the form

**Comment by Mrgaton** [comment]
i cant

**Comment by Mrgaton** [comment]
in another versions of anarchy the program works well in the form why now no?

**Comment by Mrgaton** [comment]
Pleasee fix it

**Comment by Laar-u** [comment]
> Pleasee fix it 
> 

it's not a bug dumb fuck, just run it in another thread, if you don't know how just Google it

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/123839387-5ba0d000-d90d-11eb-9519-60d09745d7ac.png)
and now i have this problem

**Comment by Mrgaton** [comment]
But i have the version 13.00 no the 12.00

**Comment by Mrgaton** [comment]
Excepción no controlada: System.IO.FileLoadException: No se puede cargar el archivo o ensamblado 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)
   en Discord.DiscordHttpClient.<SendAsync>d__4.MoveNext()
   en System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   en Discord.DiscordHttpClient.SendAsync(HttpMethod method, String endpoint, Object payload)
   en Discord.DiscordHttpClient.<GetAsync>d__5.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.UserExtensions.<GetClientUserAsync>d__2.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.UserExtensions.GetClientUser(DiscordClient client)
   en Discord.DiscordClient.set_Token(String value)
   en Discord.DiscordClient..ctor(String token, DiscordConfig config)
   en DiscordTokenLogin.TokenLoginForm.<RaidButton_Click>b__105_0()
   en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()

**Comment by Mrgaton** [comment]
ok i tried in new trheath

**Comment by Mrgaton** [comment]
and now this

Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Mensaje = Error getting value from 'Theme' on 'Discord.UserSettingsProperties'.
  Origen = Newtonsoft.Json
  Seguimiento de la pila:
   en Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   en Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   en Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   en Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   en Discord.DiscordHttpClient.<SendAsync>d__4.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.DiscordHttpClient.<PatchAsync>d__9.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.DiscordClientUser.<ChangeSettingsAsync>d__41.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.DiscordClientUser.ChangeSettings(UserSettingsProperties settings)
   en DiscordTokenLogin.TokenLoginForm.<RaidButton_Click>b__105_0()
   en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()

  Esta excepción se generó originalmente en esta pila de llamadas:
    [Código externo]

Excepción interna 1:
ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: value

**Comment by Mrgaton** [comment]
Laar-u i love u how i can help you

**Comment by Mrgaton** [comment]
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Mensaje = Error getting value from 'Theme' on 'Discord.UserSettingsProperties'.
  Origen = Newtonsoft.Json
  Seguimiento de la pila:
   en Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   en Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   en Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   en Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   en Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   en Discord.DiscordHttpClient.<SendAsync>d__4.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.DiscordHttpClient.<PatchAsync>d__9.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.DiscordClientUser.<ChangeSettingsAsync>d__41.MoveNext()
   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.DiscordClientUser.ChangeSettings(UserSettingsProperties settings)
   en DiscordTokenLogin.TokenLoginForm.<RaidButton_Click>b__105_0()
   en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   en System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Threading.ThreadHelper.ThreadStart()

  Esta excepción se generó originalmente en esta pila de llamadas:
    [Código externo]

Excepción interna 1:
ArgumentNullException: El valor no puede ser nulo.
Nombre del parámetro: value
