### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3231]
how i can turn all this options to off whith anarchy
![image](https://user-images.githubusercontent.com/68958481/123847765-3fa22c00-d917-11eb-8e59-c047e4c63c7d.png)

**Comment by not-ilinked** [comment]
Generally you can disable settings by using Client.User.ChangeSettings(), but this method doesn't cover everything. This is something i will work on in the future, but for now you'll have to mod Anarchy (or do a pull request if you feel like it)
