### ISSUE TITLE
Server Banner changable?

### ISSUE THREAD

**Issue by xenos1337** [not-ilinked/Anarchy#3233]
Is there a way to change the Server Banner? 
![image](https://user-images.githubusercontent.com/66328734/124369323-edd90900-dc6a-11eb-81de-740de6cad1cb.png)
I couldn't find anything in GuildProperties

**Comment by xenos1337** [comment]
https://github.com/not-ilinked/Anarchy/pull/3234

**Comment by venaxyt** [comment]
listen requests bro
