### ISSUE TITLE
why hitler was not sus (epic)

### ISSUE THREAD

**Issue by Stripa18** [not-ilinked/Anarchy#3235]
[Intro: Kanye East]
(it’s your boy Kanye East)
Fortnite ballz (y’all ain’t ready for this one)
Fortnite ballz
Yes sir (yep)
You know you want ‘em (you know you want ‘em)
Get your V-Bucks ready (get em up)
Yeah, yeah

[Chorus]
Fortnite ballz all in your face (aye)
Fortnite ballz all in your face (aye)
Unlock your jaw (unlock ‘em)
Lock em (unlock ‘em)
Unlock your jaw (unlock ‘em)
For the fortnite ballz

[Bridge]
You want ‘em? You want ‘em?
Fortnite ballz
You want ‘em? You want ‘em?
Sussy sussy
You want ‘em? You want ‘em?
Fortnite ballz
You want ‘em? You want ‘em?
Sussy sussy

[Verse 1]
Lil Mosey white, thats forreal
Sussy ballz, EDP get dropped like Emmett Till
You want a cupcake Candice
Then come and taste the steel
Let them ballz in your jaw and I’ll make your whole year
EDP like ‘em 13 with a soda pop
Think its hot
He got a malfunction up in his brain
Think its not, and now his back is pressed up against the wall
(Aye)
For fucking with them Fortnite ballz
(Aye)

[Chorus]
Fortnite ballz all in your face (aye)
Fortnite ballz all in your face (aye)
Unlock your jaw (unlock ‘em)
Lock em (unlock ‘em)
Unlock your jaw (unlock ‘em)
For the fortnite ballz

[Bridge]
You want ‘em? You want ‘em?
Fortnite ballz
You want ‘em? You want ‘em?
Sussy sussy
Fortnite ballz, you want ‘em?
Super sussy
Fortnite ballz, lets go

[Verse 2]
I cannot fuck up the plan
Build up the wall since I can
Shoot up ya fam
Got all the ballz and I dance
Never will land, and I just got a new fan
Please don't pretend
You do not know it's a sin
I'm already in it to win
Don't need a friend
Just need my ends
So come and put 'em in your mouth

[Chorus]
Fortnite ballz all in your face (aye)
Fortnite ballz all in your face (aye)
Unlock your jaw (unlock ‘em)
Lock em (unlock ‘em)
Unlock your jaw (unlock ‘em)
For the fortnite ballz

[Bridge]
You want ‘em? You want ‘em?
Fortnite ballz
You want ‘em? You want ‘em?
Sussy sussy
You want ‘em? You want ‘em?
Fortnite ballz
You want ‘em? You want ‘em?
Sussy sussy

**Comment by Mrgaton** [comment]
so sus
