### ISSUE TITLE
Anarchy try to load newsoft json 12.0 but  i have the 13.1

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3236]

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/124666955-09345600-deaf-11eb-8bd1-1af215c65e0a.png)

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/124669099-2159a480-deb2-11eb-9ee2-77d26bf979fb.png)



U

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/124669165-39c9bf00-deb2-11eb-97fc-338dc4f30ec2.png)

**Comment by Mrgaton** [comment]
how i can parse the public flags  to badges?

64 to HOUSE_BRAVERY

**Comment by Mrgaton** [comment]
help me plis

**Comment by not-ilinked** [comment]
Version mismatches can, as far as i'm aware, only be solved by all parties agreeing. So if you're using Newtonsoft.Json yourself, i would suggest simple downgrading to the version Anarchy uses.
