### ISSUE TITLE
Any way to get Message from reaction

### ISSUE THREAD

**Issue by xenos1337** [not-ilinked/Anarchy#3237]
I'm trying to get the DiscordMessage when using client.OnMessageReactionAdded but I couldn't find any way to get the message from the reaction does anyone have a solution?

**Comment by xenos1337** [comment]
can't you just get the message from the guild-id and message-id like the message link

**Comment by kamikos** [comment]
get the massage then its
DiscordMessage.Reactions

**Comment by xenos1337** [comment]
no I'm not trying to get the reactions from the message I want to get the message from the reaction

**Comment by not-ilinked** [comment]
The class MessageReactionUpdate has a member called MessageId. To get the full message object you'd have to either cache messages as you receive them or run client.GetChannelMessages() until you find it.
