### ISSUE TITLE
How i can change Privacy and safety setting?

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3239]
![image](https://user-images.githubusercontent.com/68958481/126522603-fa2c86b7-798f-459d-85a5-0cb9dacbaf5f.png)
i want to change all this setting pliss whith anarchy but i cant found how to do it or if is posible

**Comment by Mrgaton** [comment]
Please can someone help me @not-ilinked

**Comment by not-ilinked** [comment]
Some of these have been added to SettingsUpdate, which is the properties class used in client.User.ChangeSettings(...)

**Comment by Mrgaton** [comment]
could you put to change all the options?
and where can I see an example of how they are changed?

**Comment by Mrgaton** [comment]
And for change this options?
![image](https://user-images.githubusercontent.com/68958481/126828505-649e9fb0-eca8-487d-8fb3-522e050072aa.png)

**Comment by not-ilinked** [comment]
Many settings have not been added to the SettingsUpdate class, but i do intend to add them in the next update. If you want them right now, add them urself and make a pull request. Cheers!

**Comment by not-ilinked** [comment]
Added in https://github.com/not-ilinked/Anarchy/commit/3460206df9f8234ad36ced6e84bb4c5a4cd7663c
