### ISSUE TITLE
How FriendRequestFlags Works?

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3240]
![image](https://user-images.githubusercontent.com/68958481/126874938-605b3bb3-37d7-4d78-89f5-f68727b23807.png)
i made this code but i dont now how friendrequest flags works

**Comment by not-ilinked** [comment]
I actually forgot to make you able to change the members of FriendRequestFlags, so i'm afraid you won't be able to use that for now, lol

**Comment by Mrgaton** [comment]
Ok when you can let me know and if you can give me an example of how it would be, I would appreciate it

**Comment by Mrgaton** [comment]
Is it possible that you could ban an account with anarchy?

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/126967556-b224d11b-762c-401c-822d-527166578e5e.png)

https://github.com/discord/discord-api-docs/issues/69#issuecomment-223886862

**Comment by Mrgaton** [comment]
By the way, it would be cool if you could modify the user's bio

**Comment by ManualMap** [comment]
> 
> 
> By the way, it would be cool if you could modify the user's bio

You can do this by just doing this.

client.User.ChangeProfile(new UserProfileUpdate()
{
    Avatar = Image.FromFile("icon.png"),
    Biography = "LAARU OWNS"
});`

**Comment by not-ilinked** [comment]
> 
> 
> Is it possible that you could ban an account with anarchy?

that's worded a little strange. do you mean deleting your own account, or getting someone else's banned?

**Comment by Mrgaton** [comment]
that anarchy can ban the token you put in it

Because to delete the account you need the password and apart you can cancel by mail

**Comment by not-ilinked** [comment]
Ah, so you want to make some sort of account terminator? Generally speaking, just do some suspicious shit.

**Comment by Mrgaton** [comment]
> Ah, so you want to make some sort of account terminator? Generally speaking, just do some suspicious shit.

better forget it

**Comment by ManualMap** [comment]
> 
> 
> > Ah, so you want to make some sort of account terminator? Generally speaking, just do some suspicious shit.
> 
> better forget it

client.JoinGuild("invite");

ez disabled/phone locked lmao

**Comment by Mrgaton** [comment]
> > > Ah, so you want to make some sort of account terminator? Generally speaking, just do some suspicious shit.
> > 
> > 
> > better forget it
> 
> client.JoinGuild("invite");
> 
> ez disabled/phone locked lmao

:0 thanks

**Comment by Mrgaton** [comment]
> ![image](https://user-images.githubusercontent.com/68958481/126874938-605b3bb3-37d7-4d78-89f5-f68727b23807.png)
> i made this code but i dont now how friendrequest flags works

friend flags are done?

and I have a question i think if u change an user avatar whith anarchy the account whill be disabled can u fix itpls

**Comment by ManualMap** [comment]
> > ![image](https://user-images.githubusercontent.com/68958481/126874938-605b3bb3-37d7-4d78-89f5-f68727b23807.png)
> > i made this code but i dont now how friendrequest flags works
> 
> friend flags are done?
> 
> and I have a question i think if u change an user avatar whith anarchy the account whill be disabled can u fix itpls

it doesn't, I have this feature in my nuker and it doesn't disable the acc

**Comment by not-ilinked** [comment]
Fixed in https://github.com/not-ilinked/Anarchy/commit/a1c267a99606cc1ae71d7b6fa98738cbcab8a574
