### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by BIGDummyHead** [not-ilinked/Anarchy#3241]
Windows Defender, keeps telling me that once the software is compiled that it is a virus. Not really sure why. But you can take a look here, says it is a trojan back door, just got this out of no where for some reason.
![trojan](https://user-images.githubusercontent.com/47464673/127061405-1140d831-337b-4832-879b-2b503c92e634.png)

Not really too sure why it is saying this, just tells me that the exe contains it. I compiled this program myself, but I believe that anarchy is to blame for this, just curious as to why?

**Comment by sql69** [comment]
..

**Comment by BIGDummyHead** [comment]
Don't want to scare anyone with this, as Windows Defenders can sometimes just be a pos. 

Malwarebytes says there is nothing wrong with it. 

![scan](https://user-images.githubusercontent.com/47464673/127067864-1645a716-1cb6-4a6d-af68-44b12d490f95.png)

**Comment by not-ilinked** [comment]
This is not relevant to Anarchy.
