### ISSUE TITLE
ArgumentNullException if SlashCommand has 0 parameters present

### ISSUE THREAD

**Issue by kamikos** [not-ilinked/Anarchy#3242]
```csharp
    [SlashCommand("ex", "example")]
    public class InfoCommand : SlashCommand
    {
        [SlashParameter("something", "idk", false)]
        public string idk { get; private set; }

        public override InteractionResponseProperties Handle()
        {
             return new InteractionResponseProperties()
             {
                  Content = $"bruh",
              };
        }
    }
```
                
If I will call the command without the parameter just /ex if will produce ArgumentNullException in System.Core.dll value can't be zero

If I will call it with something /ex something: abc
it will respond with "bruh"

**Comment by not-ilinked** [comment]
Fixed this in https://github.com/not-ilinked/Anarchy/commit/c1e078defc4185721c3ce32ac2b920eb598874e5

Thanks for reporting!
