### ISSUE TITLE
Client.GetChannelMessages (async or not) locks up if the channel has no messages

### ISSUE THREAD

**Issue by CodeDiseaseDev** [not-ilinked/Anarchy#3243]
**Client.GetChannelMessages** blocks the current thread when there are no messages in the channel.

heres the code I have
```cs
IReadOnlyList<DiscordMessage> msgs = await client.GetChannelMessagesAsync(ulong.Parse(NewChannel), 50);
```

**Comment by ManualMap** [comment]
> 
> 
> **Client.GetChannelMessages** blocks the current thread when there are no messages in the channel.
> 
> heres the code I have
> 
> ```cs
> IReadOnlyList<DiscordMessage> msgs = await client.GetChannelMessagesAsync(ulong.Parse(NewChannel), 50);
> ```

or just make a try catch?

**Comment by not-ilinked** [comment]
Fixed in https://github.com/not-ilinked/Anarchy/commit/a1c267a99606cc1ae71d7b6fa98738cbcab8a574
