### ISSUE TITLE
[suggestion] Custom Exception for having 2 commands with same name 

### ISSUE THREAD

**Issue by kamikos** [not-ilinked/Anarchy#3245]
I had
```csharp
[Command("test", "test")]
```
and
```csharp
[Command("test", "test2")]
```
so this produced 

> System.ArgumentException: An item with the same key has already been added

And it took me 2 hours to realize that the command name was the issue.
For some weird-ass reason any line after touching client.CommandHandler will produce this bug for me it was 
```csharp
client.CreateCommandHandler("e");
.
.
.
using (var wc = new WebClient()) // <- ArgumentException
```

It's not a real issue I'm just retarded, but a custom Exception for this would be nice idk

**Comment by not-ilinked** [comment]
Done in https://github.com/not-ilinked/Anarchy/commit/a1c267a99606cc1ae71d7b6fa98738cbcab8a574
