### ISSUE TITLE
[QUESTION] How can you Dm a user

### ISSUE THREAD

**Issue by DaddyJinx** [not-ilinked/Anarchy#3246]

**Comment by ManualMap** [comment]
uhh

client.SendMessage(dmChannelId, "message");

or if you want to create a dm with a user and then send to that then

client.CreateDM(userId).SendMessage("message");

I believe

**Comment by sql69** [comment]
why re open

**Comment by DaddyJinx** [comment]
> uhh
> 
> client.SendMessage(dmChannelId, "message");
> 
> or if you want to create a dm with a user and then send to that then
> 
> client.CreateDM(userId).SendMessage("message");
> 
> I believe

didnt work m8 just tried both of em

**Comment by sql69** [comment]
![daddy](https://user-images.githubusercontent.com/68092911/127921185-d457d4a3-537f-472a-a349-510a344dff3f.png)

**Comment by DaddyJinx** [comment]
> why re open

nvm m8 i got brain cancer :)
also can i get a kiss :?

**Comment by ManualMap** [comment]
> 
> 
> > why re open
> 
> nvm m8 i got brain cancer :)
> also can i get a kiss :?

no kiss, that's gay.

**Comment by ManualMap** [comment]
@DaddyJinx If you really don't want to wait for other people on ur issues and stuff, better check out the docs, https://ilinked1337.gitbook.io/anarchy/
