### ISSUE TITLE
It doesn't do anything after i login (Freezes)

### ISSUE THREAD

**Issue by K1lez** [not-ilinked/Anarchy#3247]
Freezes When Logging In.

**Comment by ManualMap** [comment]
I'll assume your running it on a forms app, so login on a different thread, then it won't freeze

**Comment by K1lez** [comment]
> I'll assume your running it on a forms app, so login on a different thread, then it won't freeze

Well now it doesn't freeze if i use a different thread,
Although im still experiencing a issue where it doesnt log in or anything.
Any code after the login it does nothing.

**Comment by not-ilinked** [comment]
So your issue is the .Login() method hanging?

**Comment by not-ilinked** [comment]
Closed due to inactivity.
