### ISSUE TITLE
new discord patch; join not working

### ISSUE THREAD

**Issue by nnnewo** [not-ilinked/Anarchy#3253]
add "x-debug-options: bugReporterEnabled" to headers to fix i think

**Comment by nickjack0310** [comment]
where should i add it?

**Comment by nickjack0310** [comment]
and how can i add it if leaf.xnet does not have x-debug-options as http header

**Comment by not-ilinked** [comment]
@nnnewo simply doing that didn't help me. Anarchy.Puppeteer returns 400's even tho it's literally in the browser and has all the right headers.
