### ISSUE TITLE
allow spaces in commands/prefixes

### ISSUE THREAD

**Issue by kamikos** [not-ilinked/Anarchy#3254]
idea is to have a word as a prefix instead of a typical letter + symbol etc

prefix: `simon` 
command: `say` 
Will work ofc

prefix: `simon ` (with space)
command: `say`
Won't work

prefix: `simon` 
command: ` say` (with space)
Won't work

Workaway is client.OnMessageReceived with a mess of case switch

Lets test it with message "simon say"
```csharp
        private static void Client_OnMessageReceived(DiscordSocketClient client, MessageEventArgs args)
        {
            bool test = args.Message.Content.StartsWith(prefix); // this will be true
            List<string> parts = args.Message.Content.Split(' ').ToList(); //this removes space
            //prefix.Length should be 6 (with space) but part[0] has length of 5 (space removed by split)
            if (client.CommandHandler.Commands.TryGetValue(parts[0].Substring(prefix.Length), out DiscordCommand command))
            {
                parts.RemoveAt(0);
            }
        }
```
ok so here we will get [0] with no space and I think that's stopping spaces from working in prefixes 
![image](https://user-images.githubusercontent.com/36669411/131048287-828844c4-1caf-41eb-b393-2521eb0803a8.png)

tried to fix it myself (untested)

I replaced
https://github.com/not-ilinked/Anarchy/blob/master/Anarchy/Commands/Command/CommandHandler.cs#L38
with 
```csharp        
List<string> preParts = args.Split(new [] { Prefix }, StringSplitOptions.None).ToList();
List<string> parts = preParts[1].Split(' ').ToList();
```

**Comment by K1lez** [comment]
Just wondering what is the outcome you are trying to come with?

If you want it to be a say command, as in "simon say hello world" do:
`string filtered = args.Message.Content.Substring(prefix + 1);`

If you meant something else please correct me.

**Comment by kamikos** [comment]
yeah I did something similar 
but I meant the command handler and anarchy source

**Comment by JReverse** [comment]
Shouldn't we check if the space occurs before auto splitting it?

**Comment by not-ilinked** [comment]
And why do you want this?
