### ISSUE TITLE
Add Search Endpoint

### ISSUE THREAD

**Issue by StayBlueee** [not-ilinked/Anarchy#3256]
I think this could maybe be added in a future update, but a suggestion I have is to allow users to use the "search" endpoint in various ways.

This can be very useful for many things since it unlocks so many possibilities (I am going to list the ones I can think of):
Checking the number of messages a guild member has sent.
Check if a user is a member of a guild w/o having to check through an entire list of channel members.
Seeing if a guild member sent a particular message with a given message content.

It's a missed opportunity, and I hope the search endpoint can be supported by Anarchy in the near future.

**Comment by not-ilinked** [comment]
What specifically do you mean by "the search endpoint"? Anarchy already has .GetChannelMessages(), which has all the filters Discord has.

**Comment by StayBlueee** [comment]
> 
> 
> What specifically do you mean by "the search endpoint"? Anarchy already has .GetChannelMessages(), which has all the filters Discord has.

Yeah, I am sorry, I just didn't know how else to word it, let me explain what I meant.
![image](https://user-images.githubusercontent.com/23127866/133394969-de16d2c0-09ba-4862-9156-35f9e5926236.png)
What I meant was take advantage of the search feature that user accounts have on Discord. When you enter something that you want to search, it sends a query with the channel ID and the information regarding the search.
![image](https://user-images.githubusercontent.com/23127866/133395311-f0afd41f-b74e-4a81-ae44-32e7f1ff58c7.png)
I thought this would be useful as it would essentially eliminate a lot of hassle in particular use cases, especially when dealing with a lot of channel messages, and you are only looking for messages which meet a certain criteria.

**Comment by not-ilinked** [comment]
Anarchy already has this. The .GetChannelMessages() method allows MessageFilters as a parameter. Hope this helps :)
