### ISSUE TITLE
Cant send message in channel

### ISSUE THREAD

**Issue by DraxMultiTool** [not-ilinked/Anarchy#3257]
Hello,

I have the Problem that when the line of the Code that sends a message in the channel this error pops up: Discord.DiscordHttpException: missing access 50001, 

Please help
![0_full](https://user-images.githubusercontent.com/66033567/133212917-e0e73e38-d0dc-4012-ad5e-0de797d9272e.png)

**Comment by xenos1337** [comment]
because you can't talk in the channel, you don't have any permission.
