### ISSUE TITLE
Is it possible to ban a account by token?

### ISSUE THREAD

**Issue by DraxMultiTool** [not-ilinked/Anarchy#3259]
Like an example login in account with banned api or smth and then it banned?

**Comment by xenos1337** [comment]
Disable, or ban on a server?

**Comment by DraxMultiTool** [comment]
> Disable, or ban on a server?

Like disable the whole account

**Comment by JReverse** [comment]
@DraxMultiTool mass friend mutiple people super fast and join tons of server fast + dm people super fast

Guaranteed lock
