### ISSUE TITLE
Voice Channel Connect not working

### ISSUE THREAD

**Issue by agentbarti** [not-ilinked/Anarchy#3264]
Voice channel joining not working.

I'm using this command to join
`voiceClient.Connect(channel.Id);`

I checked if id of channel is good.
Idk how to fix this

**Comment by StayBlueee** [comment]
Make sure you have opus.dll and libsodium.dll in the same directory as the executable, and ensure that the VoiceClient you are creating is created properly.

Hope this helps.

**Comment by not-ilinked** [comment]
Are you sure you have permission to join the channel? @agentbarti

**Comment by agentbarti** [comment]
Ye i'm sure

**Comment by agentbarti** [comment]
@not-ilinked

**Comment by agentbarti** [comment]
Ye i'm using example of MusicBot

**Comment by agentbarti** [comment]
And also i tried now it and after entering command it's reply to my message in discord but in vs there is error like that :
`System.BadImageFormatException HResult=0x8007000B Message=An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B) Source=Anarchy Ślad stosu: at Discord.Media.OpusDecoder.CreateDecoder(Int32 Fs, Int32 channels, OpusError& error) at Discord.Media.OpusDecoder..ctor() at Discord.Media.DiscordVoiceClient.Connect(UInt64 channelId, VoiceConnectionProperties properties) at MusicBot.PlayCommand.Execute() in C:\Some\PlayCommand.cs:line 66 at Discord.Commands.CommandHandler.Client_OnMessageReceived(DiscordSocketClient client, MessageEventArgs args) at Discord.Gateway.DiscordSocketClient.<>c__DisplayClass246_19.<WebSocket_OnMessageReceived>b__49() at System.Threading.Tasks.Task.Execute()`

**Comment by not-ilinked** [comment]
Aha! There you have your issue: Download the c++ redist

**Comment by Mrgaton** [comment]
i have the c++ resdit and still same error
