### ISSUE TITLE
Using GetChannelMessages with a given MessageFilter takes ages to return the result

### ISSUE THREAD

**Issue by StayBlueee** [not-ilinked/Anarchy#3267]
The title pretty much sums up the issue. This is the same issue I had when I opened up the same exact issue report a couple days ago (https://github.com/not-ilinked/Anarchy/issues/3256). The main reason why I opened it is because searching messages on the Discord client (even with big servers) happens nearly instantly, regardless of channel size.

I am not sure if this because Anarchy has to generate a bunch of DiscordMember objects, or if this is something on Discord's end, or something in between, when using GetChannelMessages, it can literally take up to an hour+ to finally return the messages with the given message filter.

Is there any way around this or any advice on how to fix this? Please let me know, thanks.

**Comment by not-ilinked** [comment]
Can i get some more context? GetChannelMessages() works just fine for me

**Comment by StayBlueee** [comment]
> 
> 
> Can i get some more context? GetChannelMessages() works just fine for me

I am not sure if this requires necessarily context, but I can provide an example of what I am trying to do. There's this pretty big Discord server I am in, and I am trying to use GetChannelMessages to get messages from a given author in that channel. I tested the code in a channel with only a couple of messages, and it returned just fine, so I know my code works... But once the size of the messages in the channel reaches even a moderate size, it can hang for a very very long time as it tries to get all the messages with  the given filter.

**Comment by StayBlueee** [comment]
> 
> 
> > Can i get some more context? GetChannelMessages() works just fine for me
> 
> I am not sure if this requires necessarily context, but I can provide an example of what I am trying to do. There's this pretty big Discord server I am in, and I am trying to use GetChannelMessages to get messages from a given author in that channel. I tested the code in a channel with only a couple of messages, and it returned just fine, so I know my code works... But once the size of the messages in the channel reaches even a moderate size, it can hang for a very very long time as it tries to get all the messages with the given filter.

Addendum to my original message... This appears to not only be an issue with the MessageFilter, but with the GetChannelMessages method itself (ran some more tests).

**Comment by not-ilinked** [comment]
Have you set a limit on how many messages it should pull? It gets all the channel's messages by default, so if there's been sent a lot of messages in the channel it's obviously gonna take a while.

**Comment by StayBlueee** [comment]
> 
> 
> Have you set a limit on how many messages it should pull? It gets all the channel's messages by default, so if there's been sent a lot of messages in the channel it's obviously gonna take a while.

The problem is that even with a message filter where the person only sent a couple of messages can take forever, which is why I made the original suggestion to use the search feature, as that's almost instant.

**Comment by not-ilinked** [comment]
Again i'm somewhat unable to replicate this. It does seem to take longer for big guilds like .gg/fortnite, but that's an issue on discord's side, not mine.

**Comment by StayBlueee** [comment]
> 
> 
> Again i'm somewhat unable to replicate this. It does seem to take longer for big guilds like .gg/fortnite, but that's an issue on discord's side, not mine.

I have no idea why this is happening to me, then... I have a pretty high-end PC, and it starts to hang for 20+ minutes (I stopped the program before I could actually see how long it would take) on channels with like 50k messages total, even with a MessageFilter that should return like 10 messages in total.

If you have any suggestions on how I can fix this other than limiting the amount of messages I should be checking, I would love to hear it.

Otherwise, I guess nothing can be done.

Thanks for replying with in a short period of time, appreciate it. Sorry to be a bother.

**Comment by not-ilinked** [comment]
You can look for bugs yourself by downloading the source and placing some breakpoints, other than that i don't think you can really do anything. For the record even a terrible PC would do this just fine.
