### ISSUE TITLE
Ping not working in DM

### ISSUE THREAD

**Issue by D1og0** [not-ilinked/Anarchy#3268]
Hello, I've got a problem, when I do '-mycommand @someone' my command don't do anything.
I don't know if the issue it's because i'm retarded but yeah.

NOTE: it works when I do '-mycommand ID'

**Comment by not-ilinked** [comment]
That's because the command handler currently just parses user references as ID's, not as DiscordUser objects. I'll work on adding this.

**Comment by not-ilinked** [comment]
Done: https://github.com/not-ilinked/Anarchy/commit/a2a3817e51a104cced9240ae26c6e3815d459100
