### ISSUE TITLE
Being in too many discords causes a variety of issues

### ISSUE THREAD

**Issue by gamesensee** [not-ilinked/Anarchy#3277]
I have joined 200 servers to use this library as a nitro sniper (I know I can use like python/nodejs but I'm learning c# & this is a siq library)

When using the examples provided (eg the nitro sniper), they use 1.2gb of memory initially & slowly drops over time to around 260mb. The OnLoggedIn event does not trigger at all even after running it for 2+ minutes.

On any account that has way less servers it will load as usual & quickly but still use a lot of memory (between 200-600mb).

**Comment by not-ilinked** [comment]
Have experienced something like this myself, tho it's quite strange that you don't get logged in at all. Would it be possible for you to share the token with me so i can debug?
