### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by DaddyJinx** [not-ilinked/Anarchy#3280]
Im trying to make an account cleaner and when I remove open dms once it works fine second time returns System.NullReferenceException: 'Object reference not set to an instance of an object.'

![image](https://user-images.githubusercontent.com/83990365/139734027-3c32d38f-6bfa-499c-9680-79291811be8c.png)

**Comment by DaddyJinx** [comment]
Ive tried deleteAsync and Delete()

**Comment by LunaOnTop** [comment]
I mean that is why the try catch exists for but debugging it will ignore the try catch also you don't need (Exception) in the catch, since your not even assigning a variable to it or using it
