### ISSUE TITLE
Freezes winform app

### ISSUE THREAD

**Issue by arsh-3** [not-ilinked/Anarchy#3282]
Whenever i try to use client.login(token); command, it freezes the UI. I tried everything but wont work. I think it has no winform support, pls support winforms too!

Tested .net frameworks - 4.7, 4.7.2

**Comment by LunaOnTop** [comment]
you should really login to the client on a different thread.

**Comment by arsh-3** [comment]
> you should really login to the client on a different thread.

Its worked thank you so much!
