### ISSUE TITLE
how can i get every member from the server i wrote to command in?

### ISSUE THREAD

**Issue by DraxMultiTool** [not-ilinked/Anarchy#3288]
pleeeaseee help me im stuck with thisn problem for like a few hours

**Comment by chaosity0001** [comment]
depends, what kind of command handling are you doing, actual commands or just listening for message event and checking for message content

**Comment by DraxMultiTool** [comment]
I want to get Everswinkel username from the Server into a string..

**Comment by not-ilinked** [comment]
You'd use client.GetGuildMembers() (guild.GetMembers()) if you're on a bot account or client.GetGuildChannelMembers() (guild.GetChannelMembers()) if not
