### ISSUE TITLE
how to make mass dm all added

### ISSUE THREAD

**Issue by waleedhill** [not-ilinked/Anarchy#3289]
I would like to make a mass dm everyone that the user has added, Ive somewhat did something but I have a issue

```
                for (int i = 0; i < Relationships.Count; i++)
                {
                    if (Relationships[i].Type == Discord.RelationshipType.Friends)
                    {
                        client.SendMessage()
                    }
                }
```

the getrelationships function doesnt return the users id, so I cant use the sendmessage function because it requires the user id

Is there any way I can do this?

**Comment by chaosity0001** [comment]
cant you do like

`foreach (var relationship in Relationships) {
    if (relationship.Type == Discord.RelationshipType.Friends) {
        client.SendMessage(relationship.User.ID, "message");
    }
}`
