### ISSUE TITLE
Big servers do not exist in websocket

### ISSUE THREAD

**Issue by BomboBombone** [not-ilinked/Anarchy#3291]
The websocket does not receive any message from big servers if not for channel_create, channel_delete and channel_update events. My idea is that discord does not send data for big servers if the websocket is not compressed with zlib parameter to avoid data consumption

**Comment by BomboBombone** [comment]
Update: The compression method is not the issue apparently. Even if setting zlib-stream parameter on websocket url I still do not receive any sort of message from big servers besides "channel_update" "channel_delete" and "channel_create" events

**Comment by not-ilinked** [comment]
Use client.SubscribeToGuildEvents(). This is Discord's doing, not mine
