### ISSUE TITLE
I need help for use the friend request flags

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3295]
i want to set user freind request flags but i dont now why can someone help me

**Comment by Mrgaton** [comment]
Ok is a issue please fix it
 
i cant set the friend request flags of an account

**Comment by purpl3r0se** [comment]
> Ok is a issue please fix it
> 
> i cant set the friend request flags of an account

i don't think your supposed to be able to

**Comment by Mrgaton** [comment]
lol if for a self bot

**Comment by purpl3r0se** [comment]
what do you mean by friend request flags

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/155894666-8811a64a-5943-4fdd-90a4-16dd15962355.png)

**Comment by purpl3r0se** [comment]
> 
> ![image](https://user-images.githubusercontent.com/68958481/155894666-8811a64a-5943-4fdd-90a4-16dd15962355.png)
> 

would be nice if it was in English

**Comment by purpl3r0se** [comment]
I believe there is nothing related to this right now.
