### ISSUE TITLE
Multi Token Login

### ISSUE THREAD

**Issue by Morphine999** [not-ilinked/Anarchy#3304]
Hey, so i'm trying to make a bot spammer using anarchy, and this is my code:

                DiscordSocketClient[] client = new DiscordSocketClient[tksn.Length];
                for (int i = 0; i < client.Length; i++)
                {
                    Console.WriteLine(client[i].User.Username);
                }
                Console.Clear();
                Console.WriteLine($"[!]: Loaded {_UserAmount} Total Accounts.");
                Console.ReadLine();
                
**Whenever i run the code, it says "client[] is null".
I understand what the error is telling me, and i know how to fix it, but the reason why im here is because i wanna know if you support multi token logins**

**Comment by fazelukario** [comment]
Yes, anarchy support multi token login.

**Comment by fazelukario** [comment]
Yes, anarchy support multi token login.

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/164563441-0797be10-6051-4848-a048-0ac09d3d1ffd.png)
Hello

**Comment by Morphine999** [comment]
Ok but where did checked tokens come from

**Comment by fazelukario** [comment]
> Ok but where did checked tokens come from

From `var CheckedTokens = File.ReadAllLines("Tokens.txt");` or something like this.
