### ISSUE TITLE
Slash commands

### ISSUE THREAD

**Issue by Mr-LegitHD** [not-ilinked/Anarchy#3305]
Hi are slash commands already implemented since
`client.SendMessage(channelid, "/help");`
doesn't work currently

I tried something like message + enter on a virtual keyboard but that did not really work. We just need to add an Enter KeyPress more before sending the message then Slash commands should work

**Comment by purpl3r0se** [comment]
> Hi are slash commands already implemented since `client.SendMessage(channelid, "/help");` doesn't work currently
> 
> I tried something like message + enter on a virtual keyboard but that did not really work. We just need to add an Enter KeyPress more before sending the message then Slash commands should work

Why do you think that'd work, it's not a simple message, it's an interaction which requires different POST methods than sendmessage

**Comment by not-ilinked** [comment]
An issue for this has already been made
