### ISSUE TITLE
Voice Natives?

### ISSUE THREAD

**Issue by fazelukario** [not-ilinked/Anarchy#3307]
As you site unavailable, can you publish Voice Natives?

**Comment by JReverse** [comment]
@fazelukario https://ilinked1337.gitbook.io/anarchy/ if your looking for docs.

**Comment by fazelukario** [comment]
No, I dont looking for docs, I looking for Voice Natives (voice-related binaries)
![image](https://user-images.githubusercontent.com/46999684/165963812-39a61cec-8c0e-414e-8fb0-6aa9401e8552.png)

**Comment by Mrgaton** [comment]
i need him too please nut not linked is death

**Comment by fazelukario** [comment]
@not-ilinked How about leaving a link to download Voice Natives?

**Comment by not-ilinked** [comment]
I would if i still had the binaries lmao
