### ISSUE TITLE
MESSAGE_DELETE_BULK

### ISSUE THREAD

**Issue by 131313123** [not-ilinked/Anarchy#3308]
Whenever I launch the program, I get spammed every 5 seconds with this message:

![image](https://user-images.githubusercontent.com/65302546/168648132-619b6e13-11a4-4ff3-9231-255a2c6b4fc6.png)

Any possible fix?

Is there a way to disable such logs?

![image](https://user-images.githubusercontent.com/65302546/168650107-be89f274-e906-4710-9b28-f5b3eefed7b8.png)

**Comment by purpl3r0se** [comment]
> Whenever I launch the program, I get spammed every 5 seconds with this message:
> 
> ![image](https://user-images.githubusercontent.com/65302546/168648132-619b6e13-11a4-4ff3-9231-255a2c6b4fc6.png)
> 
> Any possible fix?
> 
> Is there a way to disable such logs?
> 
> ![image](https://user-images.githubusercontent.com/65302546/168650107-be89f274-e906-4710-9b28-f5b3eefed7b8.png)

remnants of ilinked debugging 😮

**Comment by 131313123** [comment]
> 

Can I disable/remove them somehow, or is there any "hacks" to remove them?

**Comment by Mrgaton** [comment]
> > 
> 
> Can I disable/remove them somehow, or is there any "hacks" to remove them?

Modyfy the dll and done

**Comment by Francesco2426** [comment]
its not "remnants of debugging" its events that are not being handled in the DiscordSocketClient.cs file
