### ISSUE TITLE
Bot login

### ISSUE THREAD

**Issue by Kyro999** [not-ilinked/Anarchy#3310]
Bot token login? How

**Comment by wulu-epic** [comment]
```
DiscordSocketClient client = new DiscordSocketClient();
client.Login(token)
```

**Comment by Kyro999** [comment]
..? i'm asking how do u make it login with a bot token, because when i add one it say's invalid

**Comment by purpl3r0se** [comment]
> ..? i'm asking how do u make it login with a bot token, because when i add one it say's invalid

client.Login("Bot" + token);

**Comment by wulu-epic** [comment]
> 

That means the token is invalid

**Comment by JReverse** [comment]
Close this @Kyro999 ... @purpl3r0se gave solution just clutters the issues

**Comment by CsibiNorbert** [comment]
I`m adding the **"Bot " + token**, however when I do that, it throws the following error 

**Value cannot be null. (Parameter 'Gateway intents must be provided as of API v8')**. The Config.Intents is null, what is that intents and how it can be set?
