### ISSUE TITLE
How i can reply to a message

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3312]
I want to reply a message but i dont know how i mean like this
![image](https://user-images.githubusercontent.com/68958481/171043960-f0c0601e-26c1-4540-85f0-990e8677f488.png)

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/171047608-5ca2a5d1-40e0-4179-a4fa-cf408009606d.png)
and i dont know why but this ban my account

**Comment by Mrgaton** [comment]
and not works too i mean works but i need to log in with a real discord or the custom status doenst apear

**Comment by Mrgaton** [comment]
Oh and another error
![image](https://user-images.githubusercontent.com/68958481/171060367-d9d1e1f8-3bc4-422d-9041-5e0491d1430b.png)


System.IO.FileNotFoundException: libsodium.dll was not found
   en Discord.Media.DiscordVoiceClient.Connect(UInt64 channelId, VoiceConnectionProperties properties)
   en GatitoDiscordSpammer.Program.client_OnMessageReceived(DiscordSocketClient client, MessageEventArgs args) en C:\Users\Mrgato\OneDrive\Programas\Programas de CSharp\GatitoDiscordSpammer\GatitoDiscordSpammer\Program.cs:línea 313

**Comment by Mrgaton** [comment]
another 
System.IO.FileNotFoundException: opus.dll was not found
   en Discord.Media.DiscordVoiceClient.Connect(UInt64 channelId, VoiceConnectionProperties properties)
   en GatitoDiscordSpammer.Program.client_OnMessageReceived(DiscordSocketClient client, MessageEventArgs args) en C:\Users\Mrgato\OneDrive\Programas\Programas de CSharp\GatitoDiscordSpammer\GatitoDiscordSpammer\Program.cs:línea 313

**Comment by Mrgaton** [comment]
System.IO.FileNotFoundException: ffmpeg.exe was not found
   en Discord.Media.DiscordVoiceUtils.GetAudioStream(String path)
   en GatitoDiscordSpammer.Program.client_OnMessageReceived(DiscordSocketClient client, MessageEventArgs args) en C:\Users\Mrgato\OneDrive\Programas\Programas de CSharp\GatitoDiscordSpammer\GatitoDiscordSpammer\Program.cs:línea 315

BRUUh 💀

**Comment by Mrgaton** [comment]
Ok now i have this

System.BadImageFormatException: Se ha intentado cargar un programa con un formato incorrecto. (Excepción de HRESULT: 0x8007000B)
   en Discord.Media.Sodium.SecretBoxEasy(Byte* output, Byte* input, Int64 inputLength, Byte[] nonce, Byte[] secret)
   en Discord.Media.Sodium.Encrypt(Byte[] input, Int32 inputOffset, Int32 inputLength, Byte[] output, Int32 outputOffset, Byte[] nonce, Byte[] secret)
   en Discord.Media.RTPPacketHeader.Write(Byte[] secretKey, Byte[] buffer, Int32 offset, Int32 count)
   en Discord.Media.DiscordVoiceInput.Write(Byte[] buffer, Int32 offset)
   en Discord.Media.DiscordVoiceInput.CopyFrom(Stream stream, CancellationToken cancellationToken)
   en GatitoDiscordSpammer.Program.client_OnMessageReceived(DiscordSocketClient client, MessageEventArgs args) en C:\Users\Mrgato\OneDrive\Programas\Programas de CSharp\GatitoDiscordSpammer\GatitoDiscordSpammer\Program.cs:línea 334

**Comment by Mrgaton** [comment]
And idk why but discord just keep baning my self bot and flaging their messages as posible spammer
please fix it idk if is the super proprities or what but please

**Comment by Mrgaton** [comment]
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Mensaje = Unexpected character encountered while parsing value: e. Path '', line 0, position 0.
  Origen = Newtonsoft.Json
  Seguimiento de la pila:
   en Newtonsoft.Json.JsonTextReader.ParseValue()
   en Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   en Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   en Discord.DiscordHttpResponse..ctor(Int32 statusCode, String content)
   en Discord.DiscordHttpClient.<SendAsync>d__4.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.DiscordHttpClient.<GetAsync>d__5.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.UserExtensions.<GetClientUserAsync>d__2.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   en Discord.UserExtensions.GetClientUser(DiscordClient client)
   en Discord.DiscordClient.set_Token(String value)
   en Discord.Gateway.DiscordSocketClient.Login(String token)
   en GatitoDiscordSpammer.Program.<MainAsync>d__4.MoveNext()
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en GatitoDiscordSpammer.Program.Main(String[] args)

  Esta excepción se generó originalmente en esta pila de llamadas:
    [Código externo]

**Comment by Mrgaton** [comment]
Ok idnk but now it works >:C

**Comment by JReverse** [comment]
@Mrgaton if it works close this.

**Comment by Mrgaton** [comment]
But how I reply message
