### ISSUE TITLE
issue - anarchy got fixed?

### ISSUE THREAD

**Issue by aaleaf** [not-ilinked/Anarchy#3322]
i get such a error when i try to login a user token

13.07.2022 03:16:26|Fatal|WebSocket.connect:0|An error has occurred during a TLS handshake.
13.07.2022 03:16:26|Debug|WebSocket.connect:0|WebSocketSharp.WebSocketException: An error has occurred during a TLS handshake. ---> System.Security.Authentication.AuthenticationException: SSPI call failed.

**Comment by Teckhh** [comment]
can confirm anarchy stopped working for my bot token last night

**Comment by Mrgaton** [comment]
and for my self bot too

**Comment by Mrgaton** [comment]
i think not ilinked is dead 😔

**Comment by andreas-henning** [comment]
I can NOT  confirm this. My bots are running right now.

What I can confirm is that for self-bots, after having logged out, when you log back in a new authentication token is generated. You then need to retrieve the token anew. The solution is to never log out with self-bot accounts. I don't know if this has recently changed. I don't have a lot of experience with self-bots, but I don't think this is how it worked initially.

You guys may want to test that.

Unfortunately it does seem like @not-ilinked is MIA.

**Comment by Teckhh** [comment]
More to this.

The issues is with the websocket lib - basically confirmed by @not-ilinked & an alternative is required. System.Net.WebSockets does work and will remove the error thrown on .Login - however it has no events, so someone will need to add them.

**Comment by hunter8288** [comment]
> More to this.
> 
> The issues is with the websocket lib - basically confirmed by @not-ilinked & an alternative is required. System.Net.WebSockets does work and will remove the error thrown on .Login - however it has no events, so someone will need to add them.

i fixed it, ty for info
https://github.com/hunter8288/Anarchy/blob/master/Anarchy/WebSockets/DiscordWebSocket.cs

**Comment by andreas-henning** [comment]
> spoke with Ilinked last night, he unfortunately says he has no plans to further maintain Anarchy unfortunately - but he is open for contributions. 

Being open for contributions means reviewing and accepting pull requests in a timely manner. @not-ilinked isn't doing that. That's completely fine of course, but Anarchy isn't viable as is. Somebody needs to step in and be allowed to take on that role, or we decide to make someone else's fork the new main project.

It seems you have a direct line to @not-ilinked, which IMHO makes you an ideal candidate to take over the project and handle pull requests. I'd also be willing to do this, but my lack of access to @not-ilinked and the fact that WebSockets/HTTP isn't my wheelhouse makes me less suitable.

Thoughts?

**Comment by Teckhh** [comment]
> > > spoke with Ilinked last night, he unfortunately says he has no plans to further maintain Anarchy unfortunately - but he is open for contributions.
> > 
> > 
> > Being open for contributions means reviewing and accepting pull requests in a timely manner. @not-ilinked isn't doing that. That's completely fine of course, but Anarchy isn't viable as is. Somebody needs to step in and be allowed to take on that role, or we decide to make someone else's fork the new main project.
> > It seems you have a direct line to @not-ilinked, which IMHO makes you an ideal candidate to take over the project and handle pull requests. I'd also be willing to do this, but my lack of access to @not-ilinked and the fact that WebSockets/HTTP isn't my wheelhouse makes me less suitable.
> > Thoughts?
> 
> I am in no way qualified for this unfortunately as I have quite little knowledge to do with websockets myself - and the project is no small task to maintain. I am able to contact @not-ilinked through his public telegram channel I found around a year ago, and i've been asking questions and forwarding responses here.
> 
> I let @not-ilinked know about the pull requests and will also forward him your above message as-well as ask if I can share his telegram username here. I do agree though, it would be nice for someone to step in here.

![image](https://user-images.githubusercontent.com/83503828/178960814-616b21db-3e2a-4ca3-8013-d607adb4a221.png)
His telegram channel is https://t.me/Anarchyyyyyy - his telegram is: @contrib

**Comment by not-ilinked** [comment]
Hey, found my password :)
The current fix looks fine but i'm not happy with u guys changing the namespace and stuff - that'll just mean more shit people have to swap around
Also, _socketLock is required for Anarchy to make sure that you're not overstepping discord's limits and getting urself rate limited

**Comment by andreas-henning** [comment]
> More to this.
> 
> The issues is with the websocket lib - basically confirmed by @not-ilinked & an alternative is required. System.Net.WebSockets does work and will remove the error thrown on .Login - however it has no events, so someone will need to add them.

I've not yet understood the problem. If #3323 fixes it then we can get by without replacing the websocket lib, although that would be preferable. I'd be happy to contribute towards working on replacing it if that's required.

**Comment by not-ilinked** [comment]
It's very possible that it has. I'm assuming that whoever first sent it in actually verified it, but it looks sane enough. That being said i would like to keep _socketLock and all that so shit doesn't break, so it'd be great if u could work on that :)

**Comment by andreas-henning** [comment]
> That being said i would like to keep _socketLock and all that so shit doesn't break, so it'd be great if u could work on that :)
@hunter8288 just reintroduced the locks. Looks like you're good to go with #3323.

Not sure if this was directed at me:
> but i'm not happy with u guys changing the namespace and stuff 

None of my PRs change namespaces. I did change the default namespace set in the Visual Studio csproj file. It was set to a namespace that Anarchy doesn't actually use.

**Comment by hunter8288** [comment]
it seems to work, but it would probably be better to replace it with a newer websocket library. _you can not take my pool, but just add the code at your place, it doesn’t matter to me._

**Comment by not-ilinked** [comment]
Maybe, but i think i'll go with what we have for now :)
Thanks everyone
