### ISSUE TITLE
DiscordSocketClient connection ending?

### ISSUE THREAD

**Issue by K1lez** [not-ilinked/Anarchy#3326]
I am currently making a program using the an anarchy wrapper, and am having issues, the code i'm using is shown below.

```
        static DiscordSocketClient Client = new DiscordSocketClient(new DiscordSocketConfig()
        {
            Intents = DiscordGatewayIntent.Guilds | DiscordGatewayIntent.GuildMessages | DiscordGatewayIntent.GuildVoiceStates
        });
       
        static void Main(string[] args)
        {
            Client.Login("Bot MyTokenIsHere");
            Client.SetStatus(UserStatus.Online);
            Client.SetActivity(new ActivityProperties()
            {
                Name = "you sleeping",
                Type = ActivityType.Listening,
            });
            Thread.Sleep(-1);
}
```

on the ```Client.SetStatus(UserStatus.Online);``` It throws a System.InvalidOperationException, with the message of "The current state of the connection is not open".
Nor is the discord bot online with only login and sleep.

https://i.imgur.com/eESeMj4.png

I don't understand why this issue has started occuring.

**Comment by K1lez** [comment]
Some more information while debugging this issue:

the logout event gets called with an error code of 1015 and a reason of "An exception has occurred while attempting to connect"
it doesnt matter the token or ip, idk why this is happening, can anyone help plz?

**Comment by iphqne** [comment]
try this
DiscordSocketClient.UpdatePresence(new PresenceProperties() { Status = UserStatus.Online } );

**Comment by not-ilinked** [comment]
Is this issue resolved? Looking to close the issue
