### ISSUE TITLE
anarchy dont work it doenst recive any message

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3327]
dont work please update it

**Comment by andreas-henning** [comment]
I'm using it right now and it does receive messages. Have you looked at the MessageListener example?

**Comment by Mrgaton** [comment]
im using a self bot and doent even log in

**Comment by sezonis** [comment]
I'm using the master branch which I updated to the latest and am also having a couple issues with on message. 

It is receiving messages sometimes but not always. It would sometimes fire and sometimes it won't, even when setting it to re login every hour. In the past, before the TLS changes, there were no issues whatsoever with this.

**Comment by purpl3r0se** [comment]
Receiving messages work perfectly fine for me, even after leaving online for 12 hours+

**Comment by purpl3r0se** [comment]
> Receiving messages work perfectly fine for me, even after leaving online for 12 hours+

Been well over 24 hours now still working fine, only reconnects is anarchy doing itself probably because got disconnected.

**Comment by andreas-henning** [comment]
> 

You're doing something wrong. Login is fine. I asked if you tried out the MessageListener example. You didn't answer.

**Comment by Mrgaton** [comment]
I'm on vacation and now I can't do the test my apologies

**Comment by Mrgaton** [comment]
![image](https://user-images.githubusercontent.com/68958481/186775882-be8e1cd4-17a7-417a-98df-fab268024d4a.png)
the meessages doenst works

and the status of a user doenst work too

**Comment by Mrgaton** [comment]
anithing works

**Comment by andreas-henning** [comment]
You'll need to be much more specific about what "doesn't work" means. If you can't figure out yourself what is going wrong, then a minimal example might help others figure it out.
