### ISSUE TITLE
DiscordClient & Socket not working.

### ISSUE THREAD

**Issue by 0xPuddy** [not-ilinked/Anarchy#3329]
Maybe its just me but DiscordSocket and discordclient either one will not work.

**Comment by purpl3r0se** [comment]
> Maybe its just me but DiscordSocket and discordclient either one will not work.

Can you share your code because it works perfectly fine for me.

**Comment by r3mad3dev** [comment]
DiscordClient client = new DiscordClient();
            client.Token = "token";
            client.User.SetHypesquad(Hypesquad.Brilliance);

**Comment by purpl3r0se** [comment]
> ```
>         DiscordClient client = new DiscordClient();
>         client.Token = "token";
>         client.User.SetHypesquad(Hypesquad.Brilliance);
> ```

This is completely wrong, but instead of telling you directly I'll just redirect you to the documentation because I'm too lazy rn.
Documentation: https://ilinked1337.gitbook.io/anarchy/

**Comment by r3mad3dev** [comment]
> > ```
> >         DiscordClient client = new DiscordClient();
> >         client.Token = "token";
> >         client.User.SetHypesquad(Hypesquad.Brilliance);
> > ```
> 
> This is completely wrong, but instead of telling you directly I'll just redirect you to the documentation because I'm too lazy rn. Documentation: https://ilinked1337.gitbook.io/anarchy/

`DiscordClient client = new DiscordClient("tokens can be set like this", new DiscordConfig() { RetryOnRateLimit = true });
client.Token = "or like this";

GuildInvite inv = client.JoinGuild("fortnite");
inv.Guild.Leave();`

I don't understand the problem when it show the following code above on the docs.

**Comment by V3rzeT** [comment]
Having the same issue, I think? I don't really know for sure, as the way OP described the issue barely has any details.
What happens for me is that after I try to initialize `DiscordClient` or `DiscordSocketClient` (the one I use), it gets stuck on something (no errors, just code doesn't advance to `.Login()` or anything else).

Happens on both **0.8.1.2** on .NET Framework 4.8 (old project that worked fine), and on latest version from **main branch** on .NET 6

**Comment by Mrgaton** [comment]
I confirm anarchy just dont works and needs a rework

**Comment by andreas-henning** [comment]
> narchy just dont works and needs a rework

How about fixing what you think is broken? I use it every day and at least for my needs it works fine.

**Comment by Mrgaton** [comment]
Discord socket client for self accounts don't work 🥱

**Comment by andreas-henning** [comment]
I'm using it right now for a self-bot. Have you tried the Message Listener example application.

**Comment by r3mad3dev** [comment]
> I'm using it right now for a self-bot. Have you tried the Message Listener example application.

You got discord?

**Comment by andreas-henning** [comment]
> > I'm using it right now for a self-bot. Have you tried the Message Listener example application.
> 
> You got discord?

You still interested in discord? I will delete the link if not.

**Comment by andreas-henning** [comment]
We found the problem.

Anarchy was working, but for some reason r3mad3dev was experiencing very startup times between 40 seconds and 4 minutes. This time was being wasted waiting for discord to serve the javascript assets which Anarchy downloads on startup. On my end these are downloaded within 5 seconds. I don't understand why it takes so much longer on his end. He commented out method body of SuperProperties.GetClientVersion() and startup was then instantaneous.

**Comment by purpl3r0se** [comment]
> We found the problem.
> 
> Anarchy was working, but for some reason r3mad3dev was experiencing very long startup times between 40 seconds and 4 minutes. He interrupted the startup process before Anarchy ever got around to doing its thing.
> 
> This excessive amount of time was spent waiting for discord to serve up the javascript assets which Anarchy downloads during startup to find and extract the client APIs build_number. On my end these assets are downloaded within 5 seconds. I don't know why it takes so much longer on r3mad3dev's end.
> 
> r3mad3dev commented out the method body of `SuperProperties.GetClientVersion()` and startup was then instantaneous.
> 
> I'll submit a pull request to speed this up.

It's extremely slow because his internet is bad, mine is as well and it takes ~40s or sometimes less/more, that's why I just hardcode the value.

**Comment by andreas-henning** [comment]
> > We found the problem.
> > Anarchy was working, but for some reason r3mad3dev was experiencing very long startup times between 40 seconds and 4 minutes. He interrupted the startup process before Anarchy ever got around to doing its thing.
> > This excessive amount of time was spent waiting for discord to serve up the javascript assets which Anarchy downloads during startup to find and extract the client APIs build_number. On my end these assets are downloaded within 5 seconds. I don't know why it takes so much longer on r3mad3dev's end.
> > r3mad3dev commented out the method body of `SuperProperties.GetClientVersion()` and startup was then instantaneous.
> > I'll submit a pull request to speed this up.
> 
> It's extremely slow because his internet is bad, mine is as well and it takes ~40s or sometimes less/more, that's why I just hardcode the value.

Thanks for the feedback @purpl3r0se. Appreciate it. In total I think it's around 15 MB of assets that are downloaded during startup. I find it hard to believe that this takes some people up to 4 minutes to download, even on really poor connections.

You're in the 40 second range. For you I think/hope the pull request I just submitted should make things tolerable.

**Comment by purpl3r0se** [comment]
> > > We found the problem.
> > > Anarchy was working, but for some reason r3mad3dev was experiencing very long startup times between 40 seconds and 4 minutes. He interrupted the startup process before Anarchy ever got around to doing its thing.
> > > This excessive amount of time was spent waiting for discord to serve up the javascript assets which Anarchy downloads during startup to find and extract the client APIs build_number. On my end these assets are downloaded within 5 seconds. I don't know why it takes so much longer on r3mad3dev's end.
> > > r3mad3dev commented out the method body of `SuperProperties.GetClientVersion()` and startup was then instantaneous.
> > > I'll submit a pull request to speed this up.
> > 
> > It's extremely slow because his internet is bad, mine is as well and it takes ~40s or sometimes less/more, that's why I just hardcode the value.
> 
> Thanks for the feedback @purpl3r0se. Appreciate it. In total I think it's around 15 MB of assets that are downloaded during startup. I find it hard to believe that this takes some people up to 4 minutes to download, even on really poor connections. I can't say you're wrong, but it's why it does make me hesitant to say that's the only problem.
> 
> You're in the 40 second range. For you I think/hope the pull request I just submitted should make things tolerable.

My average internet speed is like 1mb/s ofc takes longer when slower.

**Comment by andreas-henning** [comment]
> > > > We found the problem.
> > > > Anarchy was working, but for some reason r3mad3dev was experiencing very long startup times between 40 seconds and 4 minutes. He interrupted the startup process before Anarchy ever got around to doing its thing.
> > > > This excessive amount of time was spent waiting for discord to serve up the javascript assets which Anarchy downloads during startup to find and extract the client APIs build_number. On my end these assets are downloaded within 5 seconds. I don't know why it takes so much longer on r3mad3dev's end.
> > > > r3mad3dev commented out the method body of `SuperProperties.GetClientVersion()` and startup was then instantaneous.
> > > > I'll submit a pull request to speed this up.
> > > 
> > > 
> > > It's extremely slow because his internet is bad, mine is as well and it takes ~40s or sometimes less/more, that's why I just hardcode the value.
> > 
> > 
> > Thanks for the feedback @purpl3r0se. Appreciate it. In total I think it's around 15 MB of assets that are downloaded during startup. I find it hard to believe that this takes some people up to 4 minutes to download, even on really poor connections. I can't say you're wrong, but it's why it does make me hesitant to say that's the only problem.
> > You're in the 40 second range. For you I think/hope the pull request I just submitted should make things tolerable.
> 
> My average internet speed is like 1mb/s ofc takes longer when slower.

@not-ilinked just merged my pull request. If you can, let me know how things look for you now? It shouldn't download more than a MB.

**Comment by purpl3r0se** [comment]
> > > > > We found the problem.
> > > > > Anarchy was working, but for some reason r3mad3dev was experiencing very long startup times between 40 seconds and 4 minutes. He interrupted the startup process before Anarchy ever got around to doing its thing.
> > > > > This excessive amount of time was spent waiting for discord to serve up the javascript assets which Anarchy downloads during startup to find and extract the client APIs build_number. On my end these assets are downloaded within 5 seconds. I don't know why it takes so much longer on r3mad3dev's end.
> > > > > r3mad3dev commented out the method body of `SuperProperties.GetClientVersion()` and startup was then instantaneous.
> > > > > I'll submit a pull request to speed this up.
> > > > 
> > > > 
> > > > It's extremely slow because his internet is bad, mine is as well and it takes ~40s or sometimes less/more, that's why I just hardcode the value.
> > > 
> > > 
> > > Thanks for the feedback @purpl3r0se. Appreciate it. In total I think it's around 15 MB of assets that are downloaded during startup. I find it hard to believe that this takes some people up to 4 minutes to download, even on really poor connections. I can't say you're wrong, but it's why it does make me hesitant to say that's the only problem.
> > > You're in the 40 second range. For you I think/hope the pull request I just submitted should make things tolerable.
> > 
> > My average internet speed is like 1mb/s ofc takes longer when slower.
> 
> @not-ilinked just merged my pull request. If you can, let me know how things look for you now? It shouldn't download more than a MB.

Currently not on pc but I did tell ilinked to look at the pull request, that's why it got merged quite quickly.
