### ISSUE TITLE
Update Anarchy version

### ISSUE THREAD

**Issue by StayBlueee** [not-ilinked/Anarchy#3331]
The version on NuGet is outdated

**Comment by cabiste69** [comment]
there's another release by one of the contributors that supports .net 6
https://www.nuget.org/packages/Discord.Anarchy
but yeah the owner must update it

**Comment by andreas-henning** [comment]
I sent @not-ilinked the nuget package a while ago. He's not deployed it. I don't know why, but I suspect he's waiting for somebody to fix the #3330.

**Comment by not-ilinked** [comment]
Waiting for Andreas to give me a .nupkg file with the right info :)

**Comment by andreas-henning** [comment]
nupkg file given.
