### ISSUE TITLE
is this project ded?

### ISSUE THREAD

**Issue by cabiste69** [not-ilinked/Anarchy#3332]
the last commit was on the 30th of july almost a month and a half from now and the main developer doesn't seem active on github since then 
so is the project done for or is are you just taking a long break

**Comment by purpl3r0se** [comment]
> the last commit was on the 30th of july almost a month and a half from now and the main developer doesn't seem active on github since then so is the project done for or is are you just taking a long break

afaik, he doesn't work on this anymore but he accepts any contribution pull requests, which usually happen if something breaks and in some cases also is a feature update

**Comment by cabiste69** [comment]
yeah I was asking because the `SendMessage` is broken, tried it multiple times with different ways and it didn't work, i even tried using the other nuget released by a contributor and that as well didn't work

**Comment by andreas-henning** [comment]
I'm using SendMessageAsync, which is wrapped by SendMessage. I'm not having any issues.

The other nuget release you used is probably mine. I'll update it.

**Comment by cabiste69** [comment]
yeah it's yours, can you also provide a template for the appsettings.json?

**Comment by andreas-henning** [comment]
> yeah it's yours, can you also provide a template for the appsettings.json?

What settings file to you mean? The appsettings.json for the Anarchy.Tests project?

**Comment by cabiste69** [comment]
>  Anarchy, being a library, doesn't have/need a settings file.

oh ok, because i tried building it the other day and i got an error for missing values so i thought maybe i need a settings file

**Comment by andreas-henning** [comment]
Okay. No idea what that could be. Haven't seen that myself.
