### ISSUE TITLE
Creating a new instance of DiscordClient freezes thread

### ISSUE THREAD

**Issue by RadonCoding** [not-ilinked/Anarchy#3338]
The code execution stops [here](https://github.com/not-ilinked/Anarchy/blob/master/Anarchy/REST/HTTP/DiscordHttpClient.cs#L73).

**Comment by andreas-henning** [comment]
Have you tried the NicknameAnimation example?

It also uses DiscordClient and seems to work fine.

**Comment by RadonCoding** [comment]
> Have you tried the NicknameAnimation example?
> 
> It also uses DiscordClient and works fine.

thanks for the reply i'll test it

**Comment by RadonCoding** [comment]
Okay it seems the problem was with my tokens.
