### ISSUE TITLE
Doesnt work on Net framework 4.8

### ISSUE THREAD

**Issue by Mrgaton** [not-ilinked/Anarchy#3348]
Please fix

**Comment by Mrgaton** [comment]
Could not install package 'Anarchy-Wrapper 0.8.3'. You are trying to install this package in a project that has '.NETFramework,Version=v4.8' as its target, but the package does not contain assembly references or content files compatible with that framework. For more information, contact the package author.

**Comment by not-ilinked** [comment]
Is it possible to upgrade your project to .NET 6? That's what Anarchy targets now

**Comment by Mrgaton** [comment]
Why not give compatibility to the other frameworks like before?

**Comment by Mrgaton** [comment]
> Is it possible to upgrade your project to .NET 6? That's what Anarchy targets now

Please do it like before

**Comment by purpl3r0se** [comment]
> > Is it possible to upgrade your project to .NET 6? That's what Anarchy targets now
> 
> Please do it like before

.NET 6 has better performance n stuff, overall it'd be better if you start using .NET 6, rather than relying on .NET Framework

**Comment by Mrgaton** [comment]
but I'm just asking for compatibility or something

**Comment by JReverse** [comment]
Leave framework bro LMAO .NET 6 +  is the future Framework only for windows
