### ISSUE TITLE
Update is needed.

### ISSUE THREAD

**Issue by repfuel** [not-ilinked/Anarchy#3360]
Experiments endpoint,
non-discrim usernames (not out yet although the endpoints exist),
color themes,
onboarding,
activities,
family center,
guildverification,
soundboard,
and more. 

For now it is not an issue when it comes to overall use and functionality, but if you were to ever consider revamping this project, you could add these functionalities to it.

**Comment by purpl3r0se** [comment]
> Experiments endpoint,
> non-discrim usernames (not out yet although the endpoints exist),
> color themes,
> onboarding,
> activities,
> family center,
> guildverification,
> soundboard,
> and more. 
> 
> For now it is not an issue when it comes to overall use and functionality, but if you were to ever consider revamping this project, you could add these functionalities to it.
> 
> 

This project is maintained by contributors, I don't think it'll be touched by iLinked at all unless absolutely needed.

**Comment by Mrgaton** [comment]
also sending files are broken

**Comment by verticalsync** [comment]
> Experiments endpoint, non-discrim usernames (not out yet although the endpoints exist), color themes, onboarding, activities, family center, guildverification, soundboard, and more.
> 
> For now it is not an issue when it comes to overall use and functionality, but if you were to ever consider revamping this project, you could add these functionalities to it.

Non discriminator username functionality should be working fine in #3366
