### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by CrystalxCode** [not-ilinked/Anarchy#35]
Is this only usable with visual studio? I am a linux user as windows is too bad for my developing needs.

**Comment by TheBackdoor** [comment]
csharp is a programming langauge. The only thing A programming language needs is a interpreter. Download a Linux csharp interpreter, make a .cs file and compile it.

for More information just google csharp linux.

**Comment by CrystalxCode** [comment]
Alright, thank you.

**Comment by faith** [comment]
Thats now how it works, you need a .net framework to use anarchy which cant rl be used in linux atleast natively
