### ISSUE TITLE
how to get current serverid

### ISSUE THREAD

**Issue by ytmcgamer** [not-ilinked/Anarchy#37]
yeah it sounds like very easy but im trying since 2hr to get the current server id ( not channel id ) anyone know how lol

**Comment by ytmcgamer** [comment]
```cs
                    ulong serverid = Convert.ToUInt64(message.Guild.Id);
                    SocketGuild guild = client.GetCachedGuild(serverid);
``` omg ahahaa was ez but i had 2 iq sry

**Comment by not-ilinked** [comment]
Guild.Id is already a ulong, so there's no point in converting it. What's even going wrong in that piece of code? It would throw an exception if message.Guild is null, which it will be if the message was sent through DM's, but other than that i have no idea.

Please clarify .-.
