### ISSUE TITLE
Question: Creating Commands With Anarchy?

### ISSUE THREAD

**Issue by LegendModzYT** [not-ilinked/Anarchy#4]
Hey, so I am new to using Anarchy and making SelfBots in general but was wondering on how I would go about making commands using Anarchy. If you could throw me on the right path or give me an example on what to do that'd be great.

**Comment by not-ilinked** [comment]
Have a look at CommandListener in the 'Example Projects' folder ;)

**Comment by LegendModzYT** [comment]
I see you updated it from "HasPermissions" to "GetPermissions" and I'm a bit stupid so if I try to do what I did before it says "No Overload For Method GetPermissions".
