### ISSUE TITLE
'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by JReverse** [not-ilinked/Anarchy#41]
On get Presence

            foreach(var activity in client.GetPresence(client.User.Id).Activities)
            {
                Console.WriteLine(activity.Name);
            }

even tried 

Console.WriteLine(client.GetPresence(client.User.Id).Status);

any clue? there no docs in the github docs

**Comment by not-ilinked** [comment]
Sounds like a bug. Does it work when you call .GetPresence() on other users than your own?

**Comment by JReverse** [comment]
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Discord.Gateway.DiscordSocketClient.Presences.get returned null.

On  Other Users

@not-ilinked

**Comment by not-ilinked** [comment]
Are you on a user account?

**Comment by JReverse** [comment]
> Are you on a user account?

No using bot account @not-ilinked

**Comment by not-ilinked** [comment]
That's probably why then. In v8 you need to specify Gateway intents, but GUILD_PRESENCES is "priviliged" so you can't get it anyway.

https://discord.com/developers/docs/topics/gatewayateway-intents

**Comment by JReverse** [comment]
@not-ilinked I guess I'll workaround as a normal user ;/
