### ISSUE TITLE
[Improvement] Move to .Net Core / Standard For Linux Support

### ISSUE THREAD

**Issue by JReverse** [not-ilinked/Anarchy#42]
https://betanews.com/2019/05/07/future-of-dotnet/

.Net Framework shouldn't be used in the future

**Comment by not-ilinked** [comment]
https://www.theregister.com/2020/08/27/microsoft_net_5_feature_complete/

**Comment by JReverse** [comment]
@not-ilinked btw .net 5 is .net core not .framework https://docs.microsoft.com/en-us/dotnet/core/dotnet-five

https://prnt.sc/vb1u7a you may have to port stuff for Linux capability

**Comment by JReverse** [comment]
@not-ilinked https://devblogs.microsoft.com/dotnet/announcing-net-5-0/ its released 👍

**Comment by not-ilinked** [comment]
yeah i see. i'll have a look at it ig

**Comment by faith** [comment]
He made a poll in the past on his YouTube channel. Doesn't seem like hes moving it to .net core for a bit, will probably take a while porting too even if he decides to do so as hes a single developer. Feel free to make a fork and port it over if you want and open a pull request so it gets merged with this repository 😉

**Comment by JReverse** [comment]
@faith I Started porting #45

**Comment by faith** [comment]
> @faith I Started porting #45 

Great, should probably close this issue then.

**Comment by owersite** [comment]
close this issue

**Comment by stop-bark** [comment]
> close this issue

this issue will only be closed once the porting is finished I believe

**Comment by Buddelbubi** [comment]
when will it be done?

**Comment by heapwalk** [comment]
Porting this would require a lot of code removed as well since in his code there is reference to system.drawing.image which is not supported on frameworks outside of .net framework

**Comment by not-ilinked** [comment]
Does .NET core have an equivelant, @heapwalk?

**Comment by JReverse** [comment]
@not-ilinked  https://www.nuget.org/packages/System.Drawing.Common/ lol hes speaking bullshit

**Comment by heapwalk** [comment]
> Does .NET core have an equivelant, @heapwalk?

Yes, installing the `System.Drawing.Common` NuGet package. This contains `Image` and other windows drawing methods, but not all of them, I don't know which ones are included and not.

If this don't work, alternatively we can just create a addon library that extends the development on windows and contains all your image drawing methods

**Comment by JReverse** [comment]
We should wait for .Net 6 many improvements + Speed and other shit

**Comment by fazelukario** [comment]
@JReverse @not-ilinked .NET 6 Released, time to port library for Linux support!

**Comment by Cthulhu-Admin** [comment]
> Does .NET core have an equivalent, @heapwalk?

Attempts were made to make System.Drawing.Common (a thin wrapper around Windows GDI) cross-platform, but they never fully panned out. In .Net 6.0 System.Drawing.Common has been flagged Windows specific for that reason.

Microsoft's eventual cross-platform replacement will be this:

https://github.com/dotnet/Microsoft.Maui.Graphics

The best 3rd party library is:

https://github.com/SixLabors/ImageSharp

If this is what's holding the port to .Net 6.0 up, I'd be glad to submit a pull request that supports either one of these libraries, or both.

**Comment by andreas-henning** [comment]
I have ported this to .NET 6.0, including all the examples. See #3318 

This .NET 6.0 compatible package is published on nuget.org as Discord.Anarchy and also includes some new features.
https://www.nuget.org/packages/Discord.Anarchy/

Full source code here:
https://github.com/andreas-henning/Discord.Anarchy

**Comment by JReverse** [comment]
https://github.com/not-ilinked/Anarchy/pull/3318
