### ISSUE TITLE
System.PlatformNotSupportedException

### ISSUE THREAD

**Issue by Buddelbubi** [not-ilinked/Anarchy#43]
> using Discord.Gateway;
> using System;
> 
> namespace ConsoleApp2
> {
>     class Program
>     {
>         static void Main(string[] args)
>         {
>             DiscordSocketClient client = new DiscordSocketClient();
>             
>             client.Login("Censored");
>         }
>     }
> }

All it gives me is this: 
System.PlatformNotSupportedException: "Operation is not supported on this platform."

Idk if its C# or the library.. Im new to C#. I use java most times so I understand the code. 
But I've never seen an error like this.

**Comment by not-ilinked** [comment]
Are you using .NET Framework?

**Comment by Buddelbubi** [comment]
I think it said .NET Core..

**Comment by Buddelbubi** [comment]
Okay. I managed to use .NET Framework.
There is no error anymore, but no login either.
The program just closed

**Comment by ohkriss** [comment]
> 
> 
> Okay. I managed to use .NET Framework.
> There is no error anymore, but no login either.
> The program just closed

Block the main thread with `Thread.Sleep(Timeout.Infinite)` after you called `client.login()`
