### ISSUE TITLE
CommandHandler Problems. (Renamed Due To Change Of Issue.)

### ISSUE THREAD

**Issue by LegendModzYT** [not-ilinked/Anarchy#5]
I see you updated it from "HasPermissions" to "GetPermissions" and I'm a bit stupid so if I try to do what I did before it says "No Overload For Method GetPermissions".

**Comment by LegendModzYT** [comment]
Also When trying to add a command I get this error `'HelpCommand' does not implement interface member 'ICommand.Execute(DiscordSocketClient, DiscordMessage)`

**Comment by not-ilinked** [comment]
As for your first question, could you please try making it a little clearer?

The solution to your second one is adding an Execute method override, which will be executed when a command is triggered.
Something like this:
```csharp
public void Execute(DiscordSocketClient client, DiscordMessage message)
{
}
```

**Comment by LegendModzYT** [comment]
Okay so my first question was how do I check if they have a certain permission before doing a command before it was `message.Author.Member.HasPermission(DiscordMessage.DeleteChannel)`.

My second question was I did what you said and my error was fixed, thank you but there arises another problem. I have set up a custom prefix thing so the user can pick the prefix so this would be the CommandHandler `client.CreateComandHandler($"{config.Prefix}");` and while that doesn't give an error when I do `--help` it seems to do nothing. 

Appreciate you helping me, thank you.

**Comment by not-ilinked** [comment]
As for your first question then, you can now do `message.Author.Member.GetPermissions().HasFlag(DiscordPermission.apermission);`.

And have u inputted "help" as the first parameter on your command handler's Command attribute?

**Comment by LegendModzYT** [comment]
Okay thank you.

If I'm correct in understanding you're asking if I did `[Command("help")] at the top below namespace. If so then yes.

**Comment by not-ilinked** [comment]
Oooooh i think i understand now. Have you written any code inside of the Execute method?

**Comment by LegendModzYT** [comment]
Yes. I am trying to make a help command that when a user sends `help` with their prefix it sends an embed in the current channel showing the other commands etc.

**Comment by not-ilinked** [comment]
Have you called client.CreateCommandHandler()?
If you have, send me your code.

**Comment by LegendModzYT** [comment]
Will Do. Here it is.
 
        public void Execute(DiscordSocketClient client, DiscordMessage message)
        {
            if (message.Author.User.Id == client.User.Id)
            {
                TextChannel yea = client.GetChannel(channel.Id).ToTextChannel();

                EmbedMaker embedmaker = new EmbedMaker();
                embedmaker.Title = "this is a title.";
                embedmaker.Description = "description is **cool**.";
                embedmaker.AddField("yeet", "grimm selfbot.", false);
                embedmaker.Footer.Text = "grimm selfbot.";
                //embedmaker.footer.iconurl = "grimm icon for the moment";
                embedmaker.Author.IconUrl = $"{message.Author.User.Avatar.Url}";
                embedmaker.Color = Color.FromArgb(255, 20, 147);

                yea.SendMessage("", false, embedmaker);
            }
            else
            {
                return;
            }
      }

**Comment by LegendModzYT** [comment]
That's my Execute code. Is that what you wanted or did you want where I create the command handler?

**Comment by not-ilinked** [comment]
Have you called client.CreateCommandHandler()?
I think you forgot to answer my question :3

**Comment by LegendModzYT** [comment]
Oh sorry, Yes I have in my Program.cs.

**Comment by not-ilinked** [comment]
Hmmm... Honestly, i'm not entirely sure what could be the cause of the issue then. What exactly was your prefix?

**Comment by LegendModzYT** [comment]
My prefix was `--`.

**Comment by LegendModzYT** [comment]
You have any solution? Not on the beta version by the way.

**Comment by not-ilinked** [comment]
I honestly have no idea. I think the easiest way of solving the issue at this point would be using Team Viewer or AnyDesk.
Tell me if you're interested.

(oh and just a thought i had, if you have any properties in the command class with the attribute 'Parameter', tell me)

**Comment by LegendModzYT** [comment]
Well I have the `channel` parameter to get the `channel.Id`. With the anydesk thing I might be able to do that maybe tomorrow. I'll try see if the command works today for an odd reason. If it still doesn't work then we can do anydesk. Very weird problem seems to be only affecting me.

**Comment by not-ilinked** [comment]
Are you filling out that parameter when trying to use the command within Discord (in the case of a MinimalTextChannel that has to be a channel reference)? Anarchy's command handler will just ignore your command otherwise. 
If you are, contact me on Telegram (@notilinked) and we'll try the Anydesk thing.

**Comment by LegendModzYT** [comment]
I've even tried removing the parameter entirely and trying to send in a specific channel using `message.Channel.SendMessage("", false, embedmaker);` still doesn't work, it doesn't even throw an error. Is there any way to fix this without anydesk or Teamviewer? If not then I can do it whenever today.

**Comment by LegendModzYT** [comment]
If it helps this is where I create my command handler and where it is in my code. [Click Here(https://gyazo.com/6260316847676af7974358a32a3926f6).

**Comment by not-ilinked** [comment]
I think using teamviewer or anydesk would be a lot easier, but i can give u some stuff to try out:
- Put a breakpoint right after your `CreateCommandHandler` call, then check if `client.CommandHandler.Commands` contains 
your command.
- If it does, try adding listeners for event 'OnMissingParameter' and 'OnInvalidParameter', then use breakpoints to see if those are fired when using the command.

**Comment by LegendModzYT** [comment]
Well I was able to do the first part but the other I couldn't figure out how to do. Where can I contact you to get this Anydesk situation sorted tomorrow?

**Comment by not-ilinked** [comment]
My telegram is @notilinked and my discord is Shibe#1337
